//Generated by FigmaQML

import QtGraphicalEffects 1.15
import QtQuick 2.15
import QtQuick.Shapes 1.15
Rectangle {
    id: figma_501_198
    objectName:"button/simple/active"
    x:135
    y:212
    width:60
    height:60
    color: "transparent"
    clip: false 
    property Component delegate_501_196:     Shape {
        id: figma_501_196
        objectName:"back_button"
        x:0
        y:0
        width:60
        height:60
        ShapePath {
            strokeColor: "transparent"
            strokeWidth:1
            fillColor:"#ff04bfad"
            id: svgpath_figma_501_196
            fillRule: ShapePath.WindingFill
            PathSvg {
                path: "M60 30C60 46.5685 46.5685 60 30 60C13.4315 60 0 46.5685 0 30C0 13.4315 13.4315 0 30 0C46.5685 0 60 13.4315 60 30Z"
            } 
        }
    }
    property Item i_delegate_501_196
    property matrix4x4 delegate_501_196_transform: Qt.matrix4x4(Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,)
    onDelegate_501_196_transformChanged: {if(i_delegate_501_196 && i_delegate_501_196.transform != delegate_501_196_transform) i_delegate_501_196.transform = delegate_501_196_transform;}
    property real delegate_501_196_x: NaN
    onDelegate_501_196_xChanged: {if(i_delegate_501_196 && i_delegate_501_196.x != delegate_501_196_x) i_delegate_501_196.x = delegate_501_196_x;}
    property real delegate_501_196_y: NaN
    onDelegate_501_196_yChanged: {if(i_delegate_501_196 && i_delegate_501_196.y != delegate_501_196_y) i_delegate_501_196.y = delegate_501_196_y;}
    property real delegate_501_196_width: NaN
    onDelegate_501_196_widthChanged: {if(i_delegate_501_196 && i_delegate_501_196.width != delegate_501_196_width) i_delegate_501_196.width = delegate_501_196_width;}
    property real delegate_501_196_height: NaN
    onDelegate_501_196_heightChanged: {if(i_delegate_501_196 && i_delegate_501_196.height != delegate_501_196_height) i_delegate_501_196.height = delegate_501_196_height;}
    property Component delegate_501_197:     Text {
        id: figma_501_197
        objectName:"text_button"
        x:15
        y:15
        width:30
        height:30
        color:"#ffffffff"
        wrapMode: TextEdit.WordWrap
        text:"2"
        font.family: "Luxi Sans"
        font.italic: false
        font.letterSpacing: 1
        font.pixelSize: 24
        font.weight: Font.Normal
        horizontalAlignment: Text.AlignHCenter
        verticalAlignment: Text.AlignBottom
    }
    property Item i_delegate_501_197
    property matrix4x4 delegate_501_197_transform: Qt.matrix4x4(Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,)
    onDelegate_501_197_transformChanged: {if(i_delegate_501_197 && i_delegate_501_197.transform != delegate_501_197_transform) i_delegate_501_197.transform = delegate_501_197_transform;}
    property real delegate_501_197_x: NaN
    onDelegate_501_197_xChanged: {if(i_delegate_501_197 && i_delegate_501_197.x != delegate_501_197_x) i_delegate_501_197.x = delegate_501_197_x;}
    property real delegate_501_197_y: NaN
    onDelegate_501_197_yChanged: {if(i_delegate_501_197 && i_delegate_501_197.y != delegate_501_197_y) i_delegate_501_197.y = delegate_501_197_y;}
    property real delegate_501_197_width: NaN
    onDelegate_501_197_widthChanged: {if(i_delegate_501_197 && i_delegate_501_197.width != delegate_501_197_width) i_delegate_501_197.width = delegate_501_197_width;}
    property real delegate_501_197_height: NaN
    onDelegate_501_197_heightChanged: {if(i_delegate_501_197 && i_delegate_501_197.height != delegate_501_197_height) i_delegate_501_197.height = delegate_501_197_height;}
    Component.onCompleted: {
        const o_delegate_501_196 = {}
        if(!isNaN(delegate_501_196_transform.m11)) o_delegate_501_196['transform'] = delegate_501_196_transform;
        if(!isNaN(delegate_501_196_x)) o_delegate_501_196['x'] = delegate_501_196_x;
        if(!isNaN(delegate_501_196_y)) o_delegate_501_196['y'] = delegate_501_196_y;
        if(!isNaN(delegate_501_196_width)) o_delegate_501_196['width'] = delegate_501_196_width;
        if(!isNaN(delegate_501_196_height)) o_delegate_501_196['height'] = delegate_501_196_height;
        i_delegate_501_196 = delegate_501_196.createObject(this, o_delegate_501_196)
        delegate_501_196_x = Qt.binding(()=>i_delegate_501_196.x)
        delegate_501_196_y = Qt.binding(()=>i_delegate_501_196.y)
        delegate_501_196_width = Qt.binding(()=>i_delegate_501_196.width)
        delegate_501_196_height = Qt.binding(()=>i_delegate_501_196.height)
        const o_delegate_501_197 = {}
        if(!isNaN(delegate_501_197_transform.m11)) o_delegate_501_197['transform'] = delegate_501_197_transform;
        if(!isNaN(delegate_501_197_x)) o_delegate_501_197['x'] = delegate_501_197_x;
        if(!isNaN(delegate_501_197_y)) o_delegate_501_197['y'] = delegate_501_197_y;
        if(!isNaN(delegate_501_197_width)) o_delegate_501_197['width'] = delegate_501_197_width;
        if(!isNaN(delegate_501_197_height)) o_delegate_501_197['height'] = delegate_501_197_height;
        i_delegate_501_197 = delegate_501_197.createObject(this, o_delegate_501_197)
        delegate_501_197_x = Qt.binding(()=>i_delegate_501_197.x)
        delegate_501_197_y = Qt.binding(()=>i_delegate_501_197.y)
        delegate_501_197_width = Qt.binding(()=>i_delegate_501_197.width)
        delegate_501_197_height = Qt.binding(()=>i_delegate_501_197.height)
    }
}
