//Generated by FigmaQML

import QtGraphicalEffects 1.15
import QtQuick 2.15
import QtQuick.Shapes 1.15
Rectangle {
    id: figma_501_430
    objectName:"button/cancel/normal"
    x:287
    y:212
    width:60
    height:60
    color: "transparent"
    clip: false 
    property Component delegate_501_427:     Shape {
        id: figma_501_427
        objectName:"back1_button"
        x:0
        y:0
        width:60
        height:60
        ShapePath {
            strokeColor: "transparent"
            strokeWidth:1
            fillColor:"#ffffffff"
            id: svgpath_figma_501_427
            fillRule: ShapePath.WindingFill
            PathSvg {
                path: "M60 30C60 46.5685 46.5685 60 30 60C13.4315 60 0 46.5685 0 30C0 13.4315 13.4315 0 30 0C46.5685 0 60 13.4315 60 30Z"
            } 
        }
    }
    property Item i_delegate_501_427
    property matrix4x4 delegate_501_427_transform: Qt.matrix4x4(Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,)
    onDelegate_501_427_transformChanged: {if(i_delegate_501_427 && i_delegate_501_427.transform != delegate_501_427_transform) i_delegate_501_427.transform = delegate_501_427_transform;}
    property real delegate_501_427_x: NaN
    onDelegate_501_427_xChanged: {if(i_delegate_501_427 && i_delegate_501_427.x != delegate_501_427_x) i_delegate_501_427.x = delegate_501_427_x;}
    property real delegate_501_427_y: NaN
    onDelegate_501_427_yChanged: {if(i_delegate_501_427 && i_delegate_501_427.y != delegate_501_427_y) i_delegate_501_427.y = delegate_501_427_y;}
    property real delegate_501_427_width: NaN
    onDelegate_501_427_widthChanged: {if(i_delegate_501_427 && i_delegate_501_427.width != delegate_501_427_width) i_delegate_501_427.width = delegate_501_427_width;}
    property real delegate_501_427_height: NaN
    onDelegate_501_427_heightChanged: {if(i_delegate_501_427 && i_delegate_501_427.height != delegate_501_427_height) i_delegate_501_427.height = delegate_501_427_height;}
    property Component delegate_501_429:     Shape {
        id: figma_501_429
        objectName:"back2_button"
        opacity: 0.5
        x:0
        y:0
        width:60
        height:60
        ShapePath {
            strokeColor: "transparent"
            strokeWidth:1
            fillColor:"#fff25e5e"
            id: svgpath_figma_501_429
            fillRule: ShapePath.WindingFill
            PathSvg {
                path: "M60 30C60 46.5685 46.5685 60 30 60C13.4315 60 0 46.5685 0 30C0 13.4315 13.4315 0 30 0C46.5685 0 60 13.4315 60 30Z"
            } 
        }
    }
    property Item i_delegate_501_429
    property matrix4x4 delegate_501_429_transform: Qt.matrix4x4(Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,)
    onDelegate_501_429_transformChanged: {if(i_delegate_501_429 && i_delegate_501_429.transform != delegate_501_429_transform) i_delegate_501_429.transform = delegate_501_429_transform;}
    property real delegate_501_429_x: NaN
    onDelegate_501_429_xChanged: {if(i_delegate_501_429 && i_delegate_501_429.x != delegate_501_429_x) i_delegate_501_429.x = delegate_501_429_x;}
    property real delegate_501_429_y: NaN
    onDelegate_501_429_yChanged: {if(i_delegate_501_429 && i_delegate_501_429.y != delegate_501_429_y) i_delegate_501_429.y = delegate_501_429_y;}
    property real delegate_501_429_width: NaN
    onDelegate_501_429_widthChanged: {if(i_delegate_501_429 && i_delegate_501_429.width != delegate_501_429_width) i_delegate_501_429.width = delegate_501_429_width;}
    property real delegate_501_429_height: NaN
    onDelegate_501_429_heightChanged: {if(i_delegate_501_429 && i_delegate_501_429.height != delegate_501_429_height) i_delegate_501_429.height = delegate_501_429_height;}
    property Component delegate_501_428:     Text {
        id: figma_501_428
        objectName:"text_button"
        x:14
        y:15
        width:30
        height:30
        color:"#ffffffff"
        wrapMode: TextEdit.WordWrap
        text:"C"
        font.family: "Luxi Sans"
        font.italic: false
        font.letterSpacing: 1
        font.pixelSize: 24
        font.weight: Font.Normal
        horizontalAlignment: Text.AlignHCenter
        verticalAlignment: Text.AlignBottom
    }
    property Item i_delegate_501_428
    property matrix4x4 delegate_501_428_transform: Qt.matrix4x4(Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,)
    onDelegate_501_428_transformChanged: {if(i_delegate_501_428 && i_delegate_501_428.transform != delegate_501_428_transform) i_delegate_501_428.transform = delegate_501_428_transform;}
    property real delegate_501_428_x: NaN
    onDelegate_501_428_xChanged: {if(i_delegate_501_428 && i_delegate_501_428.x != delegate_501_428_x) i_delegate_501_428.x = delegate_501_428_x;}
    property real delegate_501_428_y: NaN
    onDelegate_501_428_yChanged: {if(i_delegate_501_428 && i_delegate_501_428.y != delegate_501_428_y) i_delegate_501_428.y = delegate_501_428_y;}
    property real delegate_501_428_width: NaN
    onDelegate_501_428_widthChanged: {if(i_delegate_501_428 && i_delegate_501_428.width != delegate_501_428_width) i_delegate_501_428.width = delegate_501_428_width;}
    property real delegate_501_428_height: NaN
    onDelegate_501_428_heightChanged: {if(i_delegate_501_428 && i_delegate_501_428.height != delegate_501_428_height) i_delegate_501_428.height = delegate_501_428_height;}
    Component.onCompleted: {
        const o_delegate_501_427 = {}
        if(!isNaN(delegate_501_427_transform.m11)) o_delegate_501_427['transform'] = delegate_501_427_transform;
        if(!isNaN(delegate_501_427_x)) o_delegate_501_427['x'] = delegate_501_427_x;
        if(!isNaN(delegate_501_427_y)) o_delegate_501_427['y'] = delegate_501_427_y;
        if(!isNaN(delegate_501_427_width)) o_delegate_501_427['width'] = delegate_501_427_width;
        if(!isNaN(delegate_501_427_height)) o_delegate_501_427['height'] = delegate_501_427_height;
        i_delegate_501_427 = delegate_501_427.createObject(this, o_delegate_501_427)
        delegate_501_427_x = Qt.binding(()=>i_delegate_501_427.x)
        delegate_501_427_y = Qt.binding(()=>i_delegate_501_427.y)
        delegate_501_427_width = Qt.binding(()=>i_delegate_501_427.width)
        delegate_501_427_height = Qt.binding(()=>i_delegate_501_427.height)
        const o_delegate_501_429 = {}
        if(!isNaN(delegate_501_429_transform.m11)) o_delegate_501_429['transform'] = delegate_501_429_transform;
        if(!isNaN(delegate_501_429_x)) o_delegate_501_429['x'] = delegate_501_429_x;
        if(!isNaN(delegate_501_429_y)) o_delegate_501_429['y'] = delegate_501_429_y;
        if(!isNaN(delegate_501_429_width)) o_delegate_501_429['width'] = delegate_501_429_width;
        if(!isNaN(delegate_501_429_height)) o_delegate_501_429['height'] = delegate_501_429_height;
        i_delegate_501_429 = delegate_501_429.createObject(this, o_delegate_501_429)
        delegate_501_429_x = Qt.binding(()=>i_delegate_501_429.x)
        delegate_501_429_y = Qt.binding(()=>i_delegate_501_429.y)
        delegate_501_429_width = Qt.binding(()=>i_delegate_501_429.width)
        delegate_501_429_height = Qt.binding(()=>i_delegate_501_429.height)
        const o_delegate_501_428 = {}
        if(!isNaN(delegate_501_428_transform.m11)) o_delegate_501_428['transform'] = delegate_501_428_transform;
        if(!isNaN(delegate_501_428_x)) o_delegate_501_428['x'] = delegate_501_428_x;
        if(!isNaN(delegate_501_428_y)) o_delegate_501_428['y'] = delegate_501_428_y;
        if(!isNaN(delegate_501_428_width)) o_delegate_501_428['width'] = delegate_501_428_width;
        if(!isNaN(delegate_501_428_height)) o_delegate_501_428['height'] = delegate_501_428_height;
        i_delegate_501_428 = delegate_501_428.createObject(this, o_delegate_501_428)
        delegate_501_428_x = Qt.binding(()=>i_delegate_501_428.x)
        delegate_501_428_y = Qt.binding(()=>i_delegate_501_428.y)
        delegate_501_428_width = Qt.binding(()=>i_delegate_501_428.width)
        delegate_501_428_height = Qt.binding(()=>i_delegate_501_428.height)
    }
}
