//Generated by FigmaQML

import QtGraphicalEffects 1.15
import QtQuick 2.15
import QtQuick.Shapes 1.15
Rectangle {
    id: figma_501_242
    objectName:"button/action/active"
    x:135
    y:120
    width:60
    height:60
    color: "transparent"
    clip: false 
    property Component delegate_501_236:     Shape {
        id: figma_501_236
        objectName:"back_button"
        x:0
        y:0
        width:60
        height:60
        ShapePath {
            strokeColor: "transparent"
            strokeWidth:1
            fillColor:"#fff7e425"
            id: svgpath_figma_501_236
            fillRule: ShapePath.WindingFill
            PathSvg {
                path: "M60 30C60 46.5685 46.5685 60 30 60C13.4315 60 0 46.5685 0 30C0 13.4315 13.4315 0 30 0C46.5685 0 60 13.4315 60 30Z"
            } 
        }
    }
    property Item i_delegate_501_236
    property matrix4x4 delegate_501_236_transform: Qt.matrix4x4(Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,)
    onDelegate_501_236_transformChanged: {if(i_delegate_501_236 && i_delegate_501_236.transform != delegate_501_236_transform) i_delegate_501_236.transform = delegate_501_236_transform;}
    property real delegate_501_236_x: NaN
    onDelegate_501_236_xChanged: {if(i_delegate_501_236 && i_delegate_501_236.x != delegate_501_236_x) i_delegate_501_236.x = delegate_501_236_x;}
    property real delegate_501_236_y: NaN
    onDelegate_501_236_yChanged: {if(i_delegate_501_236 && i_delegate_501_236.y != delegate_501_236_y) i_delegate_501_236.y = delegate_501_236_y;}
    property real delegate_501_236_width: NaN
    onDelegate_501_236_widthChanged: {if(i_delegate_501_236 && i_delegate_501_236.width != delegate_501_236_width) i_delegate_501_236.width = delegate_501_236_width;}
    property real delegate_501_236_height: NaN
    onDelegate_501_236_heightChanged: {if(i_delegate_501_236 && i_delegate_501_236.height != delegate_501_236_height) i_delegate_501_236.height = delegate_501_236_height;}
    property Component delegate_501_237:     Icon_30_plus_figma {
        id: figma_501_237
        objectName:"icon/30/plus"
        x:15
        y:15
        delegate_501_219:        Rectangle {
            id: figma_i501_237_501_219
            objectName:"plus"
            x:5
            y:5
            width:19
            height:19
            color: "transparent"
            clip: false 
            Shape {
                id: figma_i501_237_501_214
                objectName:"Vector 175"
                x:9
                y:0
                width:0
                height:19
                ShapePath {
                    joinStyle: ShapePath.MiterJoin
                    strokeColor: "#ffffffff"
                    strokeWidth:2
                    fillColor:"transparent"
                    id: svgpath_figma_i501_237_501_214
                    fillRule: ShapePath.WindingFill
                    PathSvg {
                        path: "M1 0C1 -0.552285 0.552285 -1 0 -1C-0.552285 -1 -1 -0.552285 -1 0L1 0ZM-1 19C-1 19.5523 -0.552285 20 0 20C0.552285 20 1 19.5523 1 19L-1 19ZM-1 0L-1 19L1 19L1 0L-1 0Z"
                    } 
                }
            }
            Shape {
                id: figma_i501_237_501_218
                objectName:"Vector 176"
                transform: Matrix4x4 {
                    matrix: Qt.matrix4x4(
                    -4.37114e-08, -1, 19, 0,
                    1, -4.37114e-08, 9.5, 0,
                    0, 0, 1, 0,
                    0, 0, 0, 1)
                }
                x:19
                y:9
                width:0
                height:19
                ShapePath {
                    joinStyle: ShapePath.MiterJoin
                    strokeColor: "#ffffffff"
                    strokeWidth:2
                    fillColor:"transparent"
                    id: svgpath_figma_i501_237_501_218
                    fillRule: ShapePath.WindingFill
                    PathSvg {
                        path: "M1 0C1 -0.552285 0.552285 -1 0 -1C-0.552285 -1 -1 -0.552285 -1 0L1 0ZM-1 19C-1 19.5523 -0.552285 20 0 20C0.552285 20 1 19.5523 1 19L-1 19ZM-1 0L-1 19L1 19L1 0L-1 0Z"
                    } 
                }
            }
        }
    }
    property Item i_delegate_501_237
    property matrix4x4 delegate_501_237_transform: Qt.matrix4x4(Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,)
    onDelegate_501_237_transformChanged: {if(i_delegate_501_237 && i_delegate_501_237.transform != delegate_501_237_transform) i_delegate_501_237.transform = delegate_501_237_transform;}
    property real delegate_501_237_x: NaN
    onDelegate_501_237_xChanged: {if(i_delegate_501_237 && i_delegate_501_237.x != delegate_501_237_x) i_delegate_501_237.x = delegate_501_237_x;}
    property real delegate_501_237_y: NaN
    onDelegate_501_237_yChanged: {if(i_delegate_501_237 && i_delegate_501_237.y != delegate_501_237_y) i_delegate_501_237.y = delegate_501_237_y;}
    property real delegate_501_237_width: NaN
    onDelegate_501_237_widthChanged: {if(i_delegate_501_237 && i_delegate_501_237.width != delegate_501_237_width) i_delegate_501_237.width = delegate_501_237_width;}
    property real delegate_501_237_height: NaN
    onDelegate_501_237_heightChanged: {if(i_delegate_501_237 && i_delegate_501_237.height != delegate_501_237_height) i_delegate_501_237.height = delegate_501_237_height;}
    Component.onCompleted: {
        const o_delegate_501_236 = {}
        if(!isNaN(delegate_501_236_transform.m11)) o_delegate_501_236['transform'] = delegate_501_236_transform;
        if(!isNaN(delegate_501_236_x)) o_delegate_501_236['x'] = delegate_501_236_x;
        if(!isNaN(delegate_501_236_y)) o_delegate_501_236['y'] = delegate_501_236_y;
        if(!isNaN(delegate_501_236_width)) o_delegate_501_236['width'] = delegate_501_236_width;
        if(!isNaN(delegate_501_236_height)) o_delegate_501_236['height'] = delegate_501_236_height;
        i_delegate_501_236 = delegate_501_236.createObject(this, o_delegate_501_236)
        delegate_501_236_x = Qt.binding(()=>i_delegate_501_236.x)
        delegate_501_236_y = Qt.binding(()=>i_delegate_501_236.y)
        delegate_501_236_width = Qt.binding(()=>i_delegate_501_236.width)
        delegate_501_236_height = Qt.binding(()=>i_delegate_501_236.height)
        const o_delegate_501_237 = {}
        if(!isNaN(delegate_501_237_transform.m11)) o_delegate_501_237['transform'] = delegate_501_237_transform;
        if(!isNaN(delegate_501_237_x)) o_delegate_501_237['x'] = delegate_501_237_x;
        if(!isNaN(delegate_501_237_y)) o_delegate_501_237['y'] = delegate_501_237_y;
        if(!isNaN(delegate_501_237_width)) o_delegate_501_237['width'] = delegate_501_237_width;
        if(!isNaN(delegate_501_237_height)) o_delegate_501_237['height'] = delegate_501_237_height;
        i_delegate_501_237 = delegate_501_237.createObject(this, o_delegate_501_237)
        delegate_501_237_x = Qt.binding(()=>i_delegate_501_237.x)
        delegate_501_237_y = Qt.binding(()=>i_delegate_501_237.y)
        delegate_501_237_width = Qt.binding(()=>i_delegate_501_237.width)
        delegate_501_237_height = Qt.binding(()=>i_delegate_501_237.height)
    }
}
