//Generated by FigmaQML

import QtGraphicalEffects 1.15
import QtQuick 2.15
import QtQuick.Shapes 1.15
Rectangle {
    id: figma_501_495
    objectName:"icon/30/equal"
    x:222
    y:75
    width:30
    height:30
    color: "transparent"
    clip: false 
    property Component delegate_501_486:     Shape {
        id: figma_501_486
        objectName:"back_action"
        x:0
        y:0
        width:30
        height:30
        ShapePath {
            strokeColor: "transparent"
            strokeWidth:1
            fillColor:"transparent"
            id: svgpath_figma_501_486
        }
    }
    property Item i_delegate_501_486
    property matrix4x4 delegate_501_486_transform: Qt.matrix4x4(Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,)
    onDelegate_501_486_transformChanged: {if(i_delegate_501_486 && i_delegate_501_486.transform != delegate_501_486_transform) i_delegate_501_486.transform = delegate_501_486_transform;}
    property real delegate_501_486_x: NaN
    onDelegate_501_486_xChanged: {if(i_delegate_501_486 && i_delegate_501_486.x != delegate_501_486_x) i_delegate_501_486.x = delegate_501_486_x;}
    property real delegate_501_486_y: NaN
    onDelegate_501_486_yChanged: {if(i_delegate_501_486 && i_delegate_501_486.y != delegate_501_486_y) i_delegate_501_486.y = delegate_501_486_y;}
    property real delegate_501_486_width: NaN
    onDelegate_501_486_widthChanged: {if(i_delegate_501_486 && i_delegate_501_486.width != delegate_501_486_width) i_delegate_501_486.width = delegate_501_486_width;}
    property real delegate_501_486_height: NaN
    onDelegate_501_486_heightChanged: {if(i_delegate_501_486 && i_delegate_501_486.height != delegate_501_486_height) i_delegate_501_486.height = delegate_501_486_height;}
    property Component delegate_501_487:     Shape {
        id: figma_501_487
        objectName:"minus"
        transform: Matrix4x4 {
            matrix: Qt.matrix4x4(
            -4.37114e-08, -1, 24.5, 0,
            1, -4.37114e-08, 19, 0,
            0, 0, 1, 0,
            0, 0, 0, 1)
        }
        x:24
        y:19
        width:0
        height:19
        ShapePath {
            joinStyle: ShapePath.MiterJoin
            strokeColor: "#ffffffff"
            strokeWidth:2
            fillColor:"transparent"
            id: svgpath_figma_501_487
            fillRule: ShapePath.WindingFill
            PathSvg {
                path: "M1 0C1 -0.552285 0.552285 -1 0 -1C-0.552285 -1 -1 -0.552285 -1 0L1 0ZM-1 19C-1 19.5523 -0.552285 20 0 20C0.552285 20 1 19.5523 1 19L-1 19ZM-1 0L-1 19L1 19L1 0L-1 0Z"
            } 
        }
    }
    property Item i_delegate_501_487
    property matrix4x4 delegate_501_487_transform: Qt.matrix4x4(Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,)
    onDelegate_501_487_transformChanged: {if(i_delegate_501_487 && i_delegate_501_487.transform != delegate_501_487_transform) i_delegate_501_487.transform = delegate_501_487_transform;}
    property real delegate_501_487_x: NaN
    onDelegate_501_487_xChanged: {if(i_delegate_501_487 && i_delegate_501_487.x != delegate_501_487_x) i_delegate_501_487.x = delegate_501_487_x;}
    property real delegate_501_487_y: NaN
    onDelegate_501_487_yChanged: {if(i_delegate_501_487 && i_delegate_501_487.y != delegate_501_487_y) i_delegate_501_487.y = delegate_501_487_y;}
    property real delegate_501_487_width: NaN
    onDelegate_501_487_widthChanged: {if(i_delegate_501_487 && i_delegate_501_487.width != delegate_501_487_width) i_delegate_501_487.width = delegate_501_487_width;}
    property real delegate_501_487_height: NaN
    onDelegate_501_487_heightChanged: {if(i_delegate_501_487 && i_delegate_501_487.height != delegate_501_487_height) i_delegate_501_487.height = delegate_501_487_height;}
    property Component delegate_501_494:     Shape {
        id: figma_501_494
        objectName:"minus"
        transform: Matrix4x4 {
            matrix: Qt.matrix4x4(
            -4.37114e-08, -1, 24.5, 0,
            1, -4.37114e-08, 11, 0,
            0, 0, 1, 0,
            0, 0, 0, 1)
        }
        x:24
        y:11
        width:0
        height:19
        ShapePath {
            joinStyle: ShapePath.MiterJoin
            strokeColor: "#ffffffff"
            strokeWidth:2
            fillColor:"transparent"
            id: svgpath_figma_501_494
            fillRule: ShapePath.WindingFill
            PathSvg {
                path: "M1 0C1 -0.552285 0.552285 -1 0 -1C-0.552285 -1 -1 -0.552285 -1 0L1 0ZM-1 19C-1 19.5523 -0.552285 20 0 20C0.552285 20 1 19.5523 1 19L-1 19ZM-1 0L-1 19L1 19L1 0L-1 0Z"
            } 
        }
    }
    property Item i_delegate_501_494
    property matrix4x4 delegate_501_494_transform: Qt.matrix4x4(Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,)
    onDelegate_501_494_transformChanged: {if(i_delegate_501_494 && i_delegate_501_494.transform != delegate_501_494_transform) i_delegate_501_494.transform = delegate_501_494_transform;}
    property real delegate_501_494_x: NaN
    onDelegate_501_494_xChanged: {if(i_delegate_501_494 && i_delegate_501_494.x != delegate_501_494_x) i_delegate_501_494.x = delegate_501_494_x;}
    property real delegate_501_494_y: NaN
    onDelegate_501_494_yChanged: {if(i_delegate_501_494 && i_delegate_501_494.y != delegate_501_494_y) i_delegate_501_494.y = delegate_501_494_y;}
    property real delegate_501_494_width: NaN
    onDelegate_501_494_widthChanged: {if(i_delegate_501_494 && i_delegate_501_494.width != delegate_501_494_width) i_delegate_501_494.width = delegate_501_494_width;}
    property real delegate_501_494_height: NaN
    onDelegate_501_494_heightChanged: {if(i_delegate_501_494 && i_delegate_501_494.height != delegate_501_494_height) i_delegate_501_494.height = delegate_501_494_height;}
    Component.onCompleted: {
        const o_delegate_501_486 = {}
        if(!isNaN(delegate_501_486_transform.m11)) o_delegate_501_486['transform'] = delegate_501_486_transform;
        if(!isNaN(delegate_501_486_x)) o_delegate_501_486['x'] = delegate_501_486_x;
        if(!isNaN(delegate_501_486_y)) o_delegate_501_486['y'] = delegate_501_486_y;
        if(!isNaN(delegate_501_486_width)) o_delegate_501_486['width'] = delegate_501_486_width;
        if(!isNaN(delegate_501_486_height)) o_delegate_501_486['height'] = delegate_501_486_height;
        i_delegate_501_486 = delegate_501_486.createObject(this, o_delegate_501_486)
        delegate_501_486_x = Qt.binding(()=>i_delegate_501_486.x)
        delegate_501_486_y = Qt.binding(()=>i_delegate_501_486.y)
        delegate_501_486_width = Qt.binding(()=>i_delegate_501_486.width)
        delegate_501_486_height = Qt.binding(()=>i_delegate_501_486.height)
        const o_delegate_501_487 = {}
        if(!isNaN(delegate_501_487_transform.m11)) o_delegate_501_487['transform'] = delegate_501_487_transform;
        if(!isNaN(delegate_501_487_x)) o_delegate_501_487['x'] = delegate_501_487_x;
        if(!isNaN(delegate_501_487_y)) o_delegate_501_487['y'] = delegate_501_487_y;
        if(!isNaN(delegate_501_487_width)) o_delegate_501_487['width'] = delegate_501_487_width;
        if(!isNaN(delegate_501_487_height)) o_delegate_501_487['height'] = delegate_501_487_height;
        i_delegate_501_487 = delegate_501_487.createObject(this, o_delegate_501_487)
        delegate_501_487_x = Qt.binding(()=>i_delegate_501_487.x)
        delegate_501_487_y = Qt.binding(()=>i_delegate_501_487.y)
        delegate_501_487_width = Qt.binding(()=>i_delegate_501_487.width)
        delegate_501_487_height = Qt.binding(()=>i_delegate_501_487.height)
        const o_delegate_501_494 = {}
        if(!isNaN(delegate_501_494_transform.m11)) o_delegate_501_494['transform'] = delegate_501_494_transform;
        if(!isNaN(delegate_501_494_x)) o_delegate_501_494['x'] = delegate_501_494_x;
        if(!isNaN(delegate_501_494_y)) o_delegate_501_494['y'] = delegate_501_494_y;
        if(!isNaN(delegate_501_494_width)) o_delegate_501_494['width'] = delegate_501_494_width;
        if(!isNaN(delegate_501_494_height)) o_delegate_501_494['height'] = delegate_501_494_height;
        i_delegate_501_494 = delegate_501_494.createObject(this, o_delegate_501_494)
        delegate_501_494_x = Qt.binding(()=>i_delegate_501_494.x)
        delegate_501_494_y = Qt.binding(()=>i_delegate_501_494.y)
        delegate_501_494_width = Qt.binding(()=>i_delegate_501_494.width)
        delegate_501_494_height = Qt.binding(()=>i_delegate_501_494.height)
    }
}
