//Generated by FigmaQML

import QtGraphicalEffects 1.15
import QtQuick 2.15
import QtQuick.Shapes 1.15
Rectangle {
    id: figma_501_475
    objectName:"icon/30/division"
    x:183
    y:75
    width:30
    height:30
    color: "transparent"
    clip: false 
    property Component delegate_501_471:     Shape {
        id: figma_501_471
        objectName:"back_action"
        x:0
        y:0
        width:30
        height:30
        ShapePath {
            strokeColor: "transparent"
            strokeWidth:1
            fillColor:"transparent"
            id: svgpath_figma_501_471
        }
    }
    property Item i_delegate_501_471
    property matrix4x4 delegate_501_471_transform: Qt.matrix4x4(Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,)
    onDelegate_501_471_transformChanged: {if(i_delegate_501_471 && i_delegate_501_471.transform != delegate_501_471_transform) i_delegate_501_471.transform = delegate_501_471_transform;}
    property real delegate_501_471_x: NaN
    onDelegate_501_471_xChanged: {if(i_delegate_501_471 && i_delegate_501_471.x != delegate_501_471_x) i_delegate_501_471.x = delegate_501_471_x;}
    property real delegate_501_471_y: NaN
    onDelegate_501_471_yChanged: {if(i_delegate_501_471 && i_delegate_501_471.y != delegate_501_471_y) i_delegate_501_471.y = delegate_501_471_y;}
    property real delegate_501_471_width: NaN
    onDelegate_501_471_widthChanged: {if(i_delegate_501_471 && i_delegate_501_471.width != delegate_501_471_width) i_delegate_501_471.width = delegate_501_471_width;}
    property real delegate_501_471_height: NaN
    onDelegate_501_471_heightChanged: {if(i_delegate_501_471 && i_delegate_501_471.height != delegate_501_471_height) i_delegate_501_471.height = delegate_501_471_height;}
    property Component delegate_501_488:     Rectangle {
        id: figma_501_488
        objectName:"division"
        x:5
        y:6
        width:19
        height:18
        color: "transparent"
        clip: false 
        Shape {
            id: figma_501_472
            objectName:"minus"
            transform: Matrix4x4 {
                matrix: Qt.matrix4x4(
                -4.37114e-08, -1, 19, 0,
                1, -4.37114e-08, 9, 0,
                0, 0, 1, 0,
                0, 0, 0, 1)
            }
            x:19
            y:9
            width:0
            height:19
            ShapePath {
                joinStyle: ShapePath.MiterJoin
                strokeColor: "#ffffffff"
                strokeWidth:2
                fillColor:"transparent"
                id: svgpath_figma_501_472
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M1 0C1 -0.552285 0.552285 -1 0 -1C-0.552285 -1 -1 -0.552285 -1 0L1 0ZM-1 19C-1 19.5523 -0.552285 20 0 20C0.552285 20 1 19.5523 1 19L-1 19ZM-1 0L-1 19L1 19L1 0L-1 0Z"
                } 
            }
        }
        Shape {
            id: figma_501_473
            objectName:"Ellipse 276"
            x:7
            y:0
            width:4
            height:4
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1
                fillColor:"#ffffffff"
                id: svgpath_figma_501_473
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M4 2C4 3.10457 3.10457 4 2 4C0.895431 4 0 3.10457 0 2C0 0.895431 0.895431 0 2 0C3.10457 0 4 0.895431 4 2Z"
                } 
            }
        }
        Shape {
            id: figma_501_474
            objectName:"Ellipse 277"
            x:7
            y:14
            width:4
            height:4
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1
                fillColor:"#ffffffff"
                id: svgpath_figma_501_474
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M4 2C4 3.10457 3.10457 4 2 4C0.895431 4 0 3.10457 0 2C0 0.895431 0.895431 0 2 0C3.10457 0 4 0.895431 4 2Z"
                } 
            }
        }
    }
    property Item i_delegate_501_488
    property matrix4x4 delegate_501_488_transform: Qt.matrix4x4(Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,)
    onDelegate_501_488_transformChanged: {if(i_delegate_501_488 && i_delegate_501_488.transform != delegate_501_488_transform) i_delegate_501_488.transform = delegate_501_488_transform;}
    property real delegate_501_488_x: NaN
    onDelegate_501_488_xChanged: {if(i_delegate_501_488 && i_delegate_501_488.x != delegate_501_488_x) i_delegate_501_488.x = delegate_501_488_x;}
    property real delegate_501_488_y: NaN
    onDelegate_501_488_yChanged: {if(i_delegate_501_488 && i_delegate_501_488.y != delegate_501_488_y) i_delegate_501_488.y = delegate_501_488_y;}
    property real delegate_501_488_width: NaN
    onDelegate_501_488_widthChanged: {if(i_delegate_501_488 && i_delegate_501_488.width != delegate_501_488_width) i_delegate_501_488.width = delegate_501_488_width;}
    property real delegate_501_488_height: NaN
    onDelegate_501_488_heightChanged: {if(i_delegate_501_488 && i_delegate_501_488.height != delegate_501_488_height) i_delegate_501_488.height = delegate_501_488_height;}
    Component.onCompleted: {
        const o_delegate_501_471 = {}
        if(!isNaN(delegate_501_471_transform.m11)) o_delegate_501_471['transform'] = delegate_501_471_transform;
        if(!isNaN(delegate_501_471_x)) o_delegate_501_471['x'] = delegate_501_471_x;
        if(!isNaN(delegate_501_471_y)) o_delegate_501_471['y'] = delegate_501_471_y;
        if(!isNaN(delegate_501_471_width)) o_delegate_501_471['width'] = delegate_501_471_width;
        if(!isNaN(delegate_501_471_height)) o_delegate_501_471['height'] = delegate_501_471_height;
        i_delegate_501_471 = delegate_501_471.createObject(this, o_delegate_501_471)
        delegate_501_471_x = Qt.binding(()=>i_delegate_501_471.x)
        delegate_501_471_y = Qt.binding(()=>i_delegate_501_471.y)
        delegate_501_471_width = Qt.binding(()=>i_delegate_501_471.width)
        delegate_501_471_height = Qt.binding(()=>i_delegate_501_471.height)
        const o_delegate_501_488 = {}
        if(!isNaN(delegate_501_488_transform.m11)) o_delegate_501_488['transform'] = delegate_501_488_transform;
        if(!isNaN(delegate_501_488_x)) o_delegate_501_488['x'] = delegate_501_488_x;
        if(!isNaN(delegate_501_488_y)) o_delegate_501_488['y'] = delegate_501_488_y;
        if(!isNaN(delegate_501_488_width)) o_delegate_501_488['width'] = delegate_501_488_width;
        if(!isNaN(delegate_501_488_height)) o_delegate_501_488['height'] = delegate_501_488_height;
        i_delegate_501_488 = delegate_501_488.createObject(this, o_delegate_501_488)
        delegate_501_488_x = Qt.binding(()=>i_delegate_501_488.x)
        delegate_501_488_y = Qt.binding(()=>i_delegate_501_488.y)
        delegate_501_488_width = Qt.binding(()=>i_delegate_501_488.width)
        delegate_501_488_height = Qt.binding(()=>i_delegate_501_488.height)
    }
}
