//Generated by FigmaQML

import QtGraphicalEffects 1.15
import QtQuick 2.15
import QtQuick.Shapes 1.15
Rectangle {
    id: figma_501_444
    objectName:"icon/30/minus"
    x:105
    y:75
    width:30
    height:30
    color: "transparent"
    clip: false 
    property Component delegate_501_440:     Shape {
        id: figma_501_440
        objectName:"back_action"
        x:0
        y:0
        width:30
        height:30
        ShapePath {
            strokeColor: "transparent"
            strokeWidth:1
            fillColor:"transparent"
            id: svgpath_figma_501_440
        }
    }
    property Item i_delegate_501_440
    property matrix4x4 delegate_501_440_transform: Qt.matrix4x4(Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,)
    onDelegate_501_440_transformChanged: {if(i_delegate_501_440 && i_delegate_501_440.transform != delegate_501_440_transform) i_delegate_501_440.transform = delegate_501_440_transform;}
    property real delegate_501_440_x: NaN
    onDelegate_501_440_xChanged: {if(i_delegate_501_440 && i_delegate_501_440.x != delegate_501_440_x) i_delegate_501_440.x = delegate_501_440_x;}
    property real delegate_501_440_y: NaN
    onDelegate_501_440_yChanged: {if(i_delegate_501_440 && i_delegate_501_440.y != delegate_501_440_y) i_delegate_501_440.y = delegate_501_440_y;}
    property real delegate_501_440_width: NaN
    onDelegate_501_440_widthChanged: {if(i_delegate_501_440 && i_delegate_501_440.width != delegate_501_440_width) i_delegate_501_440.width = delegate_501_440_width;}
    property real delegate_501_440_height: NaN
    onDelegate_501_440_heightChanged: {if(i_delegate_501_440 && i_delegate_501_440.height != delegate_501_440_height) i_delegate_501_440.height = delegate_501_440_height;}
    property Component delegate_501_443:     Shape {
        id: figma_501_443
        objectName:"minus"
        transform: Matrix4x4 {
            matrix: Qt.matrix4x4(
            -4.37114e-08, -1, 24.5, 0,
            1, -4.37114e-08, 15, 0,
            0, 0, 1, 0,
            0, 0, 0, 1)
        }
        x:24
        y:15
        width:0
        height:19
        ShapePath {
            joinStyle: ShapePath.MiterJoin
            strokeColor: "#ffffffff"
            strokeWidth:2
            fillColor:"transparent"
            id: svgpath_figma_501_443
            fillRule: ShapePath.WindingFill
            PathSvg {
                path: "M1 0C1 -0.552285 0.552285 -1 0 -1C-0.552285 -1 -1 -0.552285 -1 0L1 0ZM-1 19C-1 19.5523 -0.552285 20 0 20C0.552285 20 1 19.5523 1 19L-1 19ZM-1 0L-1 19L1 19L1 0L-1 0Z"
            } 
        }
    }
    property Item i_delegate_501_443
    property matrix4x4 delegate_501_443_transform: Qt.matrix4x4(Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,)
    onDelegate_501_443_transformChanged: {if(i_delegate_501_443 && i_delegate_501_443.transform != delegate_501_443_transform) i_delegate_501_443.transform = delegate_501_443_transform;}
    property real delegate_501_443_x: NaN
    onDelegate_501_443_xChanged: {if(i_delegate_501_443 && i_delegate_501_443.x != delegate_501_443_x) i_delegate_501_443.x = delegate_501_443_x;}
    property real delegate_501_443_y: NaN
    onDelegate_501_443_yChanged: {if(i_delegate_501_443 && i_delegate_501_443.y != delegate_501_443_y) i_delegate_501_443.y = delegate_501_443_y;}
    property real delegate_501_443_width: NaN
    onDelegate_501_443_widthChanged: {if(i_delegate_501_443 && i_delegate_501_443.width != delegate_501_443_width) i_delegate_501_443.width = delegate_501_443_width;}
    property real delegate_501_443_height: NaN
    onDelegate_501_443_heightChanged: {if(i_delegate_501_443 && i_delegate_501_443.height != delegate_501_443_height) i_delegate_501_443.height = delegate_501_443_height;}
    Component.onCompleted: {
        const o_delegate_501_440 = {}
        if(!isNaN(delegate_501_440_transform.m11)) o_delegate_501_440['transform'] = delegate_501_440_transform;
        if(!isNaN(delegate_501_440_x)) o_delegate_501_440['x'] = delegate_501_440_x;
        if(!isNaN(delegate_501_440_y)) o_delegate_501_440['y'] = delegate_501_440_y;
        if(!isNaN(delegate_501_440_width)) o_delegate_501_440['width'] = delegate_501_440_width;
        if(!isNaN(delegate_501_440_height)) o_delegate_501_440['height'] = delegate_501_440_height;
        i_delegate_501_440 = delegate_501_440.createObject(this, o_delegate_501_440)
        delegate_501_440_x = Qt.binding(()=>i_delegate_501_440.x)
        delegate_501_440_y = Qt.binding(()=>i_delegate_501_440.y)
        delegate_501_440_width = Qt.binding(()=>i_delegate_501_440.width)
        delegate_501_440_height = Qt.binding(()=>i_delegate_501_440.height)
        const o_delegate_501_443 = {}
        if(!isNaN(delegate_501_443_transform.m11)) o_delegate_501_443['transform'] = delegate_501_443_transform;
        if(!isNaN(delegate_501_443_x)) o_delegate_501_443['x'] = delegate_501_443_x;
        if(!isNaN(delegate_501_443_y)) o_delegate_501_443['y'] = delegate_501_443_y;
        if(!isNaN(delegate_501_443_width)) o_delegate_501_443['width'] = delegate_501_443_width;
        if(!isNaN(delegate_501_443_height)) o_delegate_501_443['height'] = delegate_501_443_height;
        i_delegate_501_443 = delegate_501_443.createObject(this, o_delegate_501_443)
        delegate_501_443_x = Qt.binding(()=>i_delegate_501_443.x)
        delegate_501_443_y = Qt.binding(()=>i_delegate_501_443.y)
        delegate_501_443_width = Qt.binding(()=>i_delegate_501_443.width)
        delegate_501_443_height = Qt.binding(()=>i_delegate_501_443.height)
    }
}
