//Generated by FigmaQML

import QtGraphicalEffects 1.15
import QtQuick 2.15
import QtQuick.Shapes 1.15
Rectangle {
    id: figma_501_221
    objectName:"icon/30/plus"
    x:66
    y:75
    width:30
    height:30
    color: "transparent"
    clip: false 
    property Component delegate_501_213:     Shape {
        id: figma_501_213
        objectName:"back_action"
        x:0
        y:0
        width:30
        height:30
        ShapePath {
            strokeColor: "transparent"
            strokeWidth:1
            fillColor:"transparent"
            id: svgpath_figma_501_213
        }
    }
    property Item i_delegate_501_213
    property matrix4x4 delegate_501_213_transform: Qt.matrix4x4(Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,)
    onDelegate_501_213_transformChanged: {if(i_delegate_501_213 && i_delegate_501_213.transform != delegate_501_213_transform) i_delegate_501_213.transform = delegate_501_213_transform;}
    property real delegate_501_213_x: NaN
    onDelegate_501_213_xChanged: {if(i_delegate_501_213 && i_delegate_501_213.x != delegate_501_213_x) i_delegate_501_213.x = delegate_501_213_x;}
    property real delegate_501_213_y: NaN
    onDelegate_501_213_yChanged: {if(i_delegate_501_213 && i_delegate_501_213.y != delegate_501_213_y) i_delegate_501_213.y = delegate_501_213_y;}
    property real delegate_501_213_width: NaN
    onDelegate_501_213_widthChanged: {if(i_delegate_501_213 && i_delegate_501_213.width != delegate_501_213_width) i_delegate_501_213.width = delegate_501_213_width;}
    property real delegate_501_213_height: NaN
    onDelegate_501_213_heightChanged: {if(i_delegate_501_213 && i_delegate_501_213.height != delegate_501_213_height) i_delegate_501_213.height = delegate_501_213_height;}
    property Component delegate_501_219:     Rectangle {
        id: figma_501_219
        objectName:"plus"
        x:5
        y:5
        width:19
        height:19
        color: "transparent"
        clip: false 
        Shape {
            id: figma_501_214
            objectName:"Vector 175"
            x:9
            y:0
            width:0
            height:19
            ShapePath {
                joinStyle: ShapePath.MiterJoin
                strokeColor: "#ffffffff"
                strokeWidth:2
                fillColor:"transparent"
                id: svgpath_figma_501_214
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M1 0C1 -0.552285 0.552285 -1 0 -1C-0.552285 -1 -1 -0.552285 -1 0L1 0ZM-1 19C-1 19.5523 -0.552285 20 0 20C0.552285 20 1 19.5523 1 19L-1 19ZM-1 0L-1 19L1 19L1 0L-1 0Z"
                } 
            }
        }
        Shape {
            id: figma_501_218
            objectName:"Vector 176"
            transform: Matrix4x4 {
                matrix: Qt.matrix4x4(
                -4.37114e-08, -1, 19, 0,
                1, -4.37114e-08, 9.5, 0,
                0, 0, 1, 0,
                0, 0, 0, 1)
            }
            x:19
            y:9
            width:0
            height:19
            ShapePath {
                joinStyle: ShapePath.MiterJoin
                strokeColor: "#ffffffff"
                strokeWidth:2
                fillColor:"transparent"
                id: svgpath_figma_501_218
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M1 0C1 -0.552285 0.552285 -1 0 -1C-0.552285 -1 -1 -0.552285 -1 0L1 0ZM-1 19C-1 19.5523 -0.552285 20 0 20C0.552285 20 1 19.5523 1 19L-1 19ZM-1 0L-1 19L1 19L1 0L-1 0Z"
                } 
            }
        }
    }
    property Item i_delegate_501_219
    property matrix4x4 delegate_501_219_transform: Qt.matrix4x4(Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,)
    onDelegate_501_219_transformChanged: {if(i_delegate_501_219 && i_delegate_501_219.transform != delegate_501_219_transform) i_delegate_501_219.transform = delegate_501_219_transform;}
    property real delegate_501_219_x: NaN
    onDelegate_501_219_xChanged: {if(i_delegate_501_219 && i_delegate_501_219.x != delegate_501_219_x) i_delegate_501_219.x = delegate_501_219_x;}
    property real delegate_501_219_y: NaN
    onDelegate_501_219_yChanged: {if(i_delegate_501_219 && i_delegate_501_219.y != delegate_501_219_y) i_delegate_501_219.y = delegate_501_219_y;}
    property real delegate_501_219_width: NaN
    onDelegate_501_219_widthChanged: {if(i_delegate_501_219 && i_delegate_501_219.width != delegate_501_219_width) i_delegate_501_219.width = delegate_501_219_width;}
    property real delegate_501_219_height: NaN
    onDelegate_501_219_heightChanged: {if(i_delegate_501_219 && i_delegate_501_219.height != delegate_501_219_height) i_delegate_501_219.height = delegate_501_219_height;}
    Component.onCompleted: {
        const o_delegate_501_213 = {}
        if(!isNaN(delegate_501_213_transform.m11)) o_delegate_501_213['transform'] = delegate_501_213_transform;
        if(!isNaN(delegate_501_213_x)) o_delegate_501_213['x'] = delegate_501_213_x;
        if(!isNaN(delegate_501_213_y)) o_delegate_501_213['y'] = delegate_501_213_y;
        if(!isNaN(delegate_501_213_width)) o_delegate_501_213['width'] = delegate_501_213_width;
        if(!isNaN(delegate_501_213_height)) o_delegate_501_213['height'] = delegate_501_213_height;
        i_delegate_501_213 = delegate_501_213.createObject(this, o_delegate_501_213)
        delegate_501_213_x = Qt.binding(()=>i_delegate_501_213.x)
        delegate_501_213_y = Qt.binding(()=>i_delegate_501_213.y)
        delegate_501_213_width = Qt.binding(()=>i_delegate_501_213.width)
        delegate_501_213_height = Qt.binding(()=>i_delegate_501_213.height)
        const o_delegate_501_219 = {}
        if(!isNaN(delegate_501_219_transform.m11)) o_delegate_501_219['transform'] = delegate_501_219_transform;
        if(!isNaN(delegate_501_219_x)) o_delegate_501_219['x'] = delegate_501_219_x;
        if(!isNaN(delegate_501_219_y)) o_delegate_501_219['y'] = delegate_501_219_y;
        if(!isNaN(delegate_501_219_width)) o_delegate_501_219['width'] = delegate_501_219_width;
        if(!isNaN(delegate_501_219_height)) o_delegate_501_219['height'] = delegate_501_219_height;
        i_delegate_501_219 = delegate_501_219.createObject(this, o_delegate_501_219)
        delegate_501_219_x = Qt.binding(()=>i_delegate_501_219.x)
        delegate_501_219_y = Qt.binding(()=>i_delegate_501_219.y)
        delegate_501_219_width = Qt.binding(()=>i_delegate_501_219.width)
        delegate_501_219_height = Qt.binding(()=>i_delegate_501_219.height)
    }
}
