//Generated by FigmaQML

import QtGraphicalEffects 1.15
import QtQuick 2.15
import QtQuick.Shapes 1.15
Rectangle {
    id: figma_501_558
    objectName:"icon/30/plus_minus"
    x:300
    y:75
    width:30
    height:30
    color: "transparent"
    clip: false 
    property Component delegate_501_549:     Shape {
        id: figma_501_549
        objectName:"back_action"
        x:0
        y:0
        width:30
        height:30
        ShapePath {
            strokeColor: "transparent"
            strokeWidth:1
            fillColor:"transparent"
            id: svgpath_figma_501_549
        }
    }
    property Item i_delegate_501_549
    property matrix4x4 delegate_501_549_transform: Qt.matrix4x4(Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,)
    onDelegate_501_549_transformChanged: {if(i_delegate_501_549 && i_delegate_501_549.transform != delegate_501_549_transform) i_delegate_501_549.transform = delegate_501_549_transform;}
    property real delegate_501_549_x: NaN
    onDelegate_501_549_xChanged: {if(i_delegate_501_549 && i_delegate_501_549.x != delegate_501_549_x) i_delegate_501_549.x = delegate_501_549_x;}
    property real delegate_501_549_y: NaN
    onDelegate_501_549_yChanged: {if(i_delegate_501_549 && i_delegate_501_549.y != delegate_501_549_y) i_delegate_501_549.y = delegate_501_549_y;}
    property real delegate_501_549_width: NaN
    onDelegate_501_549_widthChanged: {if(i_delegate_501_549 && i_delegate_501_549.width != delegate_501_549_width) i_delegate_501_549.width = delegate_501_549_width;}
    property real delegate_501_549_height: NaN
    onDelegate_501_549_heightChanged: {if(i_delegate_501_549 && i_delegate_501_549.height != delegate_501_549_height) i_delegate_501_549.height = delegate_501_549_height;}
    property Component delegate_501_550:     Rectangle {
        id: figma_501_550
        objectName:"plus_minus"
        x:4
        y:7
        width:22
        height:16
        color: "transparent"
        clip: false 
        Shape {
            id: figma_501_551
            objectName:"Vector 177"
            x:8
            y:0
            width:6
            height:16
            ShapePath {
                joinStyle: ShapePath.MiterJoin
                strokeColor: "#ffffffff"
                strokeWidth:2
                fillColor:"transparent"
                id: svgpath_figma_501_551
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M6.93633 0.351123C7.13025 -0.165997 6.86824 -0.742409 6.35112 -0.936329C5.834 -1.13025 5.25759 -0.868244 5.06367 -0.351123L6.93633 0.351123ZM-0.936329 15.6489C-1.13025 16.166 -0.868244 16.7424 -0.351123 16.9363C0.165997 17.1302 0.742409 16.8682 0.936329 16.3511L-0.936329 15.6489ZM5.06367 -0.351123L-0.936329 15.6489L0.936329 16.3511L6.93633 0.351123L5.06367 -0.351123Z"
                } 
            }
        }
        Rectangle {
            id: figma_501_556
            objectName:"plus"
            x:0
            y:0
            width:8
            height:8
            color: "transparent"
            clip: false 
            Shape {
                id: figma_501_554
                objectName:"Vector 178"
                x:4
                y:0
                width:0
                height:8
                ShapePath {
                    joinStyle: ShapePath.MiterJoin
                    strokeColor: "#ffffffff"
                    strokeWidth:2
                    fillColor:"transparent"
                    id: svgpath_figma_501_554
                    fillRule: ShapePath.WindingFill
                    PathSvg {
                        path: "M1 0C1 -0.552285 0.552285 -1 0 -1C-0.552285 -1 -1 -0.552285 -1 0L1 0ZM-1 8C-1 8.55229 -0.552285 9 0 9C0.552285 9 1 8.55229 1 8L-1 8ZM-1 0L-1 8L1 8L1 0L-1 0Z"
                    } 
                }
            }
            Shape {
                id: figma_501_555
                objectName:"Vector 179"
                transform: Matrix4x4 {
                    matrix: Qt.matrix4x4(
                    -4.37114e-08, -1, 8, 0,
                    1, -4.37114e-08, 4, 0,
                    0, 0, 1, 0,
                    0, 0, 0, 1)
                }
                x:8
                y:4
                width:0
                height:8
                ShapePath {
                    joinStyle: ShapePath.MiterJoin
                    strokeColor: "#ffffffff"
                    strokeWidth:2
                    fillColor:"transparent"
                    id: svgpath_figma_501_555
                    fillRule: ShapePath.WindingFill
                    PathSvg {
                        path: "M1 0C1 -0.552285 0.552285 -1 0 -1C-0.552285 -1 -1 -0.552285 -1 0L1 0ZM-1 8C-1 8.55229 -0.552285 9 0 9C0.552285 9 1 8.55229 1 8L-1 8ZM-1 0L-1 8L1 8L1 0L-1 0Z"
                    } 
                }
            }
        }
        Shape {
            id: figma_501_557
            objectName:"minus"
            transform: Matrix4x4 {
                matrix: Qt.matrix4x4(
                -4.37114e-08, -1, 22, 0,
                1, -4.37114e-08, 12, 0,
                0, 0, 1, 0,
                0, 0, 0, 1)
            }
            x:22
            y:12
            width:0
            height:8
            ShapePath {
                joinStyle: ShapePath.MiterJoin
                strokeColor: "#ffffffff"
                strokeWidth:2
                fillColor:"transparent"
                id: svgpath_figma_501_557
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M1 0C1 -0.552285 0.552285 -1 0 -1C-0.552285 -1 -1 -0.552285 -1 0L1 0ZM-1 8C-1 8.55229 -0.552285 9 0 9C0.552285 9 1 8.55229 1 8L-1 8ZM-1 0L-1 8L1 8L1 0L-1 0Z"
                } 
            }
        }
    }
    property Item i_delegate_501_550
    property matrix4x4 delegate_501_550_transform: Qt.matrix4x4(Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,)
    onDelegate_501_550_transformChanged: {if(i_delegate_501_550 && i_delegate_501_550.transform != delegate_501_550_transform) i_delegate_501_550.transform = delegate_501_550_transform;}
    property real delegate_501_550_x: NaN
    onDelegate_501_550_xChanged: {if(i_delegate_501_550 && i_delegate_501_550.x != delegate_501_550_x) i_delegate_501_550.x = delegate_501_550_x;}
    property real delegate_501_550_y: NaN
    onDelegate_501_550_yChanged: {if(i_delegate_501_550 && i_delegate_501_550.y != delegate_501_550_y) i_delegate_501_550.y = delegate_501_550_y;}
    property real delegate_501_550_width: NaN
    onDelegate_501_550_widthChanged: {if(i_delegate_501_550 && i_delegate_501_550.width != delegate_501_550_width) i_delegate_501_550.width = delegate_501_550_width;}
    property real delegate_501_550_height: NaN
    onDelegate_501_550_heightChanged: {if(i_delegate_501_550 && i_delegate_501_550.height != delegate_501_550_height) i_delegate_501_550.height = delegate_501_550_height;}
    Component.onCompleted: {
        const o_delegate_501_549 = {}
        if(!isNaN(delegate_501_549_transform.m11)) o_delegate_501_549['transform'] = delegate_501_549_transform;
        if(!isNaN(delegate_501_549_x)) o_delegate_501_549['x'] = delegate_501_549_x;
        if(!isNaN(delegate_501_549_y)) o_delegate_501_549['y'] = delegate_501_549_y;
        if(!isNaN(delegate_501_549_width)) o_delegate_501_549['width'] = delegate_501_549_width;
        if(!isNaN(delegate_501_549_height)) o_delegate_501_549['height'] = delegate_501_549_height;
        i_delegate_501_549 = delegate_501_549.createObject(this, o_delegate_501_549)
        delegate_501_549_x = Qt.binding(()=>i_delegate_501_549.x)
        delegate_501_549_y = Qt.binding(()=>i_delegate_501_549.y)
        delegate_501_549_width = Qt.binding(()=>i_delegate_501_549.width)
        delegate_501_549_height = Qt.binding(()=>i_delegate_501_549.height)
        const o_delegate_501_550 = {}
        if(!isNaN(delegate_501_550_transform.m11)) o_delegate_501_550['transform'] = delegate_501_550_transform;
        if(!isNaN(delegate_501_550_x)) o_delegate_501_550['x'] = delegate_501_550_x;
        if(!isNaN(delegate_501_550_y)) o_delegate_501_550['y'] = delegate_501_550_y;
        if(!isNaN(delegate_501_550_width)) o_delegate_501_550['width'] = delegate_501_550_width;
        if(!isNaN(delegate_501_550_height)) o_delegate_501_550['height'] = delegate_501_550_height;
        i_delegate_501_550 = delegate_501_550.createObject(this, o_delegate_501_550)
        delegate_501_550_x = Qt.binding(()=>i_delegate_501_550.x)
        delegate_501_550_y = Qt.binding(()=>i_delegate_501_550.y)
        delegate_501_550_width = Qt.binding(()=>i_delegate_501_550.width)
        delegate_501_550_height = Qt.binding(()=>i_delegate_501_550.height)
    }
}
