//Generated by FigmaQML

import QtGraphicalEffects 1.15
import QtQuick 2.15
import QtQuick.Shapes 1.15
Rectangle {
    id: figma_15_58
    objectName:"Icons"
    x:-2678
    y:0
    width:1300
    height:1700
    color:"#ffb8bdc0"
    clip: false 
    Status_bar_figma {
        id: figma_15_186
        objectName:"Status bar"
    }
    Button_simple_normal_figma {
        id: figma_501_191
        objectName:"button/simple/normal"
    }
    Button_simple_active_figma {
        id: figma_501_198
        objectName:"button/simple/active"
    }
    Button_cancel_active_figma {
        id: figma_501_422
        objectName:"button/cancel/active"
    }
    Button_cancel_normal_figma {
        id: figma_501_430
        objectName:"button/cancel/normal"
    }
    Button_action_normal_figma {
        id: figma_501_227
        objectName:"button/action/normal"
    }
    Button_action_active_figma {
        id: figma_501_242
        objectName:"button/action/active"
    }
    Icon_30_plus_figma {
        id: figma_501_221
        objectName:"icon/30/plus"
    }
    Icon_30_minus_figma {
        id: figma_501_444
        objectName:"icon/30/minus"
    }
    Icon_30_multiplication_figma {
        id: figma_501_460
        objectName:"icon/30/multiplication"
    }
    Icon_30_division_figma {
        id: figma_501_475
        objectName:"icon/30/division"
    }
    Icon_30_equal_figma {
        id: figma_501_495
        objectName:"icon/30/equal"
    }
    Icon_30_percent_figma {
        id: figma_501_512
        objectName:"icon/30/percent"
    }
    Icon_30_plus_minus_figma {
        id: figma_501_558
        objectName:"icon/30/plus_minus"
    }
    Icon_30_bkt_figma {
        id: figma_501_584
        objectName:"icon/30/bkt"
    }
}
