//Generated by FigmaQML

import QtGraphicalEffects 1.15
import QtQuick 2.15
import QtQuick.Shapes 1.15
Rectangle {
    id: figma_424_868
    objectName:"Colors"
    x:-3358
    y:0
    width:622
    height:700
    color:"#ffb8bdc0"
    clip: false 
    Rectangle {
        id: figma_424_936
        objectName:"Theme_1"
        x:46
        y:41
        width:400
        height:430
        color: "transparent"
        clip: false 
        Rectangle {
            id: figma_424_937
            objectName:"theme_1_1"
            x:0
            y:0
            width:400
            height:30
            color: "transparent"
            clip: false 
            Shape {
                id: figma_424_938
                objectName:"Rectangle 240"
                x:0
                y:0
                width:400
                height:30
                ShapePath {
                    strokeColor: "transparent"
                    strokeWidth:1
                    fillColor:"#ff024873"
                    id: svgpath_figma_424_938
                    fillRule: ShapePath.WindingFill
                    PathSvg {
                        path: "M0 0L400 0L400 30L0 30L0 0Z"
                    } 
                }
            }
            Text {
                id: figma_424_939
                objectName:"#024873"
                x:316
                y:5
                width:64
                height:19
                color:"#ffffffff"
                wrapMode: TextEdit.WordWrap
                text:"#024873"
                font.family: "Luxi Sans"
                font.italic: false
                font.letterSpacing: 0
                font.pixelSize: 16
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignLeft
                verticalAlignment: Text.AlignTop
            }
            Text {
                id: figma_424_940
                objectName:"Theme_1_1"
                x:15
                y:5
                width:82
                height:19
                color:"#ffffffff"
                wrapMode: TextEdit.WordWrap
                text:"Theme_1_1"
                font.family: "Luxi Sans"
                font.italic: false
                font.letterSpacing: 0
                font.pixelSize: 16
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignLeft
                verticalAlignment: Text.AlignTop
            }
        }
        Rectangle {
            id: figma_424_941
            objectName:"theme_1_2"
            x:0
            y:40
            width:400
            height:30
            color: "transparent"
            clip: false 
            Shape {
                id: figma_424_942
                objectName:"Rectangle 240"
                x:0
                y:0
                width:400
                height:30
                ShapePath {
                    strokeColor: "transparent"
                    strokeWidth:1
                    fillColor:"#ff0889a6"
                    id: svgpath_figma_424_942
                    fillRule: ShapePath.WindingFill
                    PathSvg {
                        path: "M0 0L400 0L400 30L0 30L0 0Z"
                    } 
                }
            }
            Text {
                id: figma_424_943
                objectName:"#0889A6"
                x:316
                y:5
                width:66
                height:19
                color:"#ffffffff"
                wrapMode: TextEdit.WordWrap
                text:"#0889A6"
                font.family: "Luxi Sans"
                font.italic: false
                font.letterSpacing: 0
                font.pixelSize: 16
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignLeft
                verticalAlignment: Text.AlignTop
            }
            Text {
                id: figma_424_944
                objectName:"Theme_1_2"
                x:15
                y:5
                width:82
                height:19
                color:"#ffffffff"
                wrapMode: TextEdit.WordWrap
                text:"Theme_1_2"
                font.family: "Luxi Sans"
                font.italic: false
                font.letterSpacing: 0
                font.pixelSize: 16
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignLeft
                verticalAlignment: Text.AlignTop
            }
        }
        Rectangle {
            id: figma_424_945
            objectName:"theme_1_3"
            x:0
            y:80
            width:400
            height:30
            color: "transparent"
            clip: false 
            Shape {
                id: figma_424_946
                objectName:"Rectangle 240"
                x:0
                y:0
                width:400
                height:30
                ShapePath {
                    strokeColor: "transparent"
                    strokeWidth:1
                    fillColor:"#ff04bfad"
                    id: svgpath_figma_424_946
                    fillRule: ShapePath.WindingFill
                    PathSvg {
                        path: "M0 0L400 0L400 30L0 30L0 0Z"
                    } 
                }
            }
            Text {
                id: figma_424_947
                objectName:"#04BFAD"
                x:316
                y:5
                width:67
                height:19
                color:"#ffffffff"
                wrapMode: TextEdit.WordWrap
                text:"#04BFAD"
                font.family: "Luxi Sans"
                font.italic: false
                font.letterSpacing: 0
                font.pixelSize: 16
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignLeft
                verticalAlignment: Text.AlignTop
            }
            Text {
                id: figma_424_948
                objectName:"Theme_1_3"
                x:15
                y:5
                width:82
                height:19
                color:"#ffffffff"
                wrapMode: TextEdit.WordWrap
                text:"Theme_1_3"
                font.family: "Luxi Sans"
                font.italic: false
                font.letterSpacing: 0
                font.pixelSize: 16
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignLeft
                verticalAlignment: Text.AlignTop
            }
        }
        Rectangle {
            id: figma_424_949
            objectName:"theme_1_4"
            x:0
            y:120
            width:400
            height:30
            color: "transparent"
            clip: false 
            Shape {
                id: figma_424_950
                objectName:"Rectangle 240"
                x:0
                y:0
                width:400
                height:30
                ShapePath {
                    strokeColor: "transparent"
                    strokeWidth:1
                    fillColor:"#ffb0d1d8"
                    id: svgpath_figma_424_950
                    fillRule: ShapePath.WindingFill
                    PathSvg {
                        path: "M0 0L400 0L400 30L0 30L0 0Z"
                    } 
                }
            }
            Text {
                id: figma_424_951
                objectName:"#B0D1D8"
                x:316
                y:5
                width:68
                height:19
                color:"#ffffffff"
                wrapMode: TextEdit.WordWrap
                text:"#B0D1D8"
                font.family: "Luxi Sans"
                font.italic: false
                font.letterSpacing: 0
                font.pixelSize: 16
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignLeft
                verticalAlignment: Text.AlignTop
            }
            Text {
                id: figma_424_952
                objectName:"Theme_1_4"
                x:15
                y:5
                width:82
                height:19
                color:"#ffffffff"
                wrapMode: TextEdit.WordWrap
                text:"Theme_1_4"
                font.family: "Luxi Sans"
                font.italic: false
                font.letterSpacing: 0
                font.pixelSize: 16
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignLeft
                verticalAlignment: Text.AlignTop
            }
        }
        Rectangle {
            id: figma_424_953
            objectName:"theme_1_5"
            x:0
            y:160
            width:400
            height:30
            color: "transparent"
            clip: false 
            Shape {
                id: figma_424_954
                objectName:"Rectangle 240"
                x:0
                y:0
                width:400
                height:30
                ShapePath {
                    strokeColor: "transparent"
                    strokeWidth:1
                    fillColor:"#fff25e5e"
                    id: svgpath_figma_424_954
                    fillRule: ShapePath.WindingFill
                    PathSvg {
                        path: "M0 0L400 0L400 30L0 30L0 0Z"
                    } 
                }
            }
            Text {
                id: figma_424_955
                objectName:"#F25E5E"
                x:316
                y:5
                width:64
                height:19
                color:"#ffffffff"
                wrapMode: TextEdit.WordWrap
                text:"#F25E5E"
                font.family: "Luxi Sans"
                font.italic: false
                font.letterSpacing: 0
                font.pixelSize: 16
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignLeft
                verticalAlignment: Text.AlignTop
            }
            Text {
                id: figma_424_956
                objectName:"Theme_1_5"
                x:15
                y:5
                width:82
                height:19
                color:"#ffffffff"
                wrapMode: TextEdit.WordWrap
                text:"Theme_1_5"
                font.family: "Luxi Sans"
                font.italic: false
                font.letterSpacing: 0
                font.pixelSize: 16
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignLeft
                verticalAlignment: Text.AlignTop
            }
        }
        Rectangle {
            id: figma_424_957
            objectName:"theme_1_6"
            x:0
            y:200
            width:400
            height:30
            color: "transparent"
            clip: false 
            Shape {
                id: figma_424_958
                objectName:"Rectangle 240"
                x:0
                y:0
                width:400
                height:30
                ShapePath {
                    strokeColor: "transparent"
                    strokeWidth:1
                    fillColor:"#ffffffff"
                    id: svgpath_figma_424_958
                    fillRule: ShapePath.WindingFill
                    PathSvg {
                        path: "M0 0L400 0L400 30L0 30L0 0Z"
                    } 
                }
            }
            Text {
                id: figma_424_959
                objectName:"#FFFFFF"
                x:316
                y:5
                width:63
                height:19
                color:"#ff000000"
                wrapMode: TextEdit.WordWrap
                text:"#FFFFFF"
                font.family: "Luxi Sans"
                font.italic: false
                font.letterSpacing: 0
                font.pixelSize: 16
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignLeft
                verticalAlignment: Text.AlignTop
            }
            Text {
                id: figma_424_960
                objectName:"Theme_1_6"
                x:15
                y:5
                width:82
                height:19
                color:"#ff000000"
                wrapMode: TextEdit.WordWrap
                text:"Theme_1_6"
                font.family: "Luxi Sans"
                font.italic: false
                font.letterSpacing: 0
                font.pixelSize: 16
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignLeft
                verticalAlignment: Text.AlignTop
            }
        }
        Rectangle {
            id: figma_424_961
            objectName:"Theme_1_add_1"
            x:0
            y:240
            width:400
            height:30
            color: "transparent"
            clip: false 
            Shape {
                id: figma_424_962
                objectName:"Rectangle 240"
                x:0
                y:0
                width:400
                height:30
                ShapePath {
                    strokeColor: "transparent"
                    strokeWidth:1
                    fillColor:"#ff00f79c"
                    id: svgpath_figma_424_962
                    fillRule: ShapePath.WindingFill
                    PathSvg {
                        path: "M0 0L400 0L400 30L0 30L0 0Z"
                    } 
                }
            }
            Text {
                id: figma_424_963
                objectName:"#00F79C"
                x:316
                y:5
                width:66
                height:19
                color:"#ffffffff"
                wrapMode: TextEdit.WordWrap
                text:"#00F79C"
                font.family: "Luxi Sans"
                font.italic: false
                font.letterSpacing: 0
                font.pixelSize: 16
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignLeft
                verticalAlignment: Text.AlignTop
            }
            Text {
                id: figma_424_964
                objectName:"Theme_1_add_1"
                x:15
                y:5
                width:116
                height:19
                color:"#ffffffff"
                wrapMode: TextEdit.WordWrap
                text:"Theme_1_add_1"
                font.family: "Luxi Sans"
                font.italic: false
                font.letterSpacing: 0
                font.pixelSize: 16
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignLeft
                verticalAlignment: Text.AlignTop
            }
        }
        Rectangle {
            id: figma_424_965
            objectName:"Theme_1_add_2"
            x:0
            y:280
            width:400
            height:30
            color: "transparent"
            clip: false 
            Shape {
                id: figma_424_966
                objectName:"Rectangle 240"
                x:0
                y:0
                width:400
                height:30
                ShapePath {
                    strokeColor: "transparent"
                    strokeWidth:1
                    fillColor:"#fff7e425"
                    id: svgpath_figma_424_966
                    fillRule: ShapePath.WindingFill
                    PathSvg {
                        path: "M0 0L400 0L400 30L0 30L0 0Z"
                    } 
                }
            }
            Text {
                id: figma_424_967
                objectName:"#F7E425"
                x:316
                y:5
                width:64
                height:19
                color:"#ffffffff"
                wrapMode: TextEdit.WordWrap
                text:"#F7E425"
                font.family: "Luxi Sans"
                font.italic: false
                font.letterSpacing: 0
                font.pixelSize: 16
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignLeft
                verticalAlignment: Text.AlignTop
            }
            Text {
                id: figma_424_968
                objectName:"Theme_1_add_2"
                x:15
                y:5
                width:116
                height:19
                color:"#ffffffff"
                wrapMode: TextEdit.WordWrap
                text:"Theme_1_add_2"
                font.family: "Luxi Sans"
                font.italic: false
                font.letterSpacing: 0
                font.pixelSize: 16
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignLeft
                verticalAlignment: Text.AlignTop
            }
        }
        Rectangle {
            id: figma_424_969
            objectName:"theme_1_3_30%"
            x:0
            y:320
            width:400
            height:30
            color: "transparent"
            clip: false 
            Shape {
                id: figma_424_970
                objectName:"Rectangle 240"
                x:0
                y:0
                width:400
                height:30
                ShapePath {
                    strokeColor: "transparent"
                    strokeWidth:1
                    fillColor:"#4d04bfad"
                    id: svgpath_figma_424_970
                    fillRule: ShapePath.WindingFill
                    PathSvg {
                        path: "M0 0L400 0L400 30L0 30L0 0Z"
                    } 
                }
            }
            Text {
                id: figma_424_971
                objectName:"#04BFAD"
                x:316
                y:5
                width:67
                height:19
                color:"#ffffffff"
                wrapMode: TextEdit.WordWrap
                text:"#04BFAD"
                font.family: "Luxi Sans"
                font.italic: false
                font.letterSpacing: 0
                font.pixelSize: 16
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignLeft
                verticalAlignment: Text.AlignTop
            }
            Text {
                id: figma_424_972
                objectName:"Theme_1_3_30%"
                x:15
                y:5
                width:143
                height:19
                color:"#ffffffff"
                wrapMode: TextEdit.WordWrap
                text:"Theme_1_3_30%"
                font.family: "Luxi Sans"
                font.italic: false
                font.letterSpacing: 0
                font.pixelSize: 16
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignLeft
                verticalAlignment: Text.AlignTop
            }
        }
        Rectangle {
            id: figma_424_973
            objectName:"theme_1_1_30%"
            x:0
            y:360
            width:400
            height:30
            color: "transparent"
            clip: false 
            Shape {
                id: figma_424_974
                objectName:"Rectangle 240"
                x:0
                y:0
                width:400
                height:30
                ShapePath {
                    strokeColor: "transparent"
                    strokeWidth:1
                    fillColor:"#4d024873"
                    id: svgpath_figma_424_974
                    fillRule: ShapePath.WindingFill
                    PathSvg {
                        path: "M0 0L400 0L400 30L0 30L0 0Z"
                    } 
                }
            }
            Text {
                id: figma_424_975
                objectName:"#024873"
                x:316
                y:5
                width:64
                height:19
                color:"#ffffffff"
                wrapMode: TextEdit.WordWrap
                text:"#024873"
                font.family: "Luxi Sans"
                font.italic: false
                font.letterSpacing: 0
                font.pixelSize: 16
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignLeft
                verticalAlignment: Text.AlignTop
            }
            Text {
                id: figma_424_976
                objectName:"Theme_1_1_30%"
                x:15
                y:5
                width:119
                height:19
                color:"#ffffffff"
                wrapMode: TextEdit.WordWrap
                text:"Theme_1_1_30%"
                font.family: "Luxi Sans"
                font.italic: false
                font.letterSpacing: 0
                font.pixelSize: 16
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignLeft
                verticalAlignment: Text.AlignTop
            }
        }
        Rectangle {
            id: figma_424_977
            objectName:"theme_1_4_50%"
            x:0
            y:400
            width:400
            height:30
            color: "transparent"
            clip: false 
            Shape {
                id: figma_424_978
                objectName:"Rectangle 240"
                x:0
                y:0
                width:400
                height:30
                ShapePath {
                    strokeColor: "transparent"
                    strokeWidth:1
                    fillColor:"#80b0d1d8"
                    id: svgpath_figma_424_978
                    fillRule: ShapePath.WindingFill
                    PathSvg {
                        path: "M0 0L400 0L400 30L0 30L0 0Z"
                    } 
                }
            }
            Text {
                id: figma_424_979
                objectName:"#B0D1D8"
                x:316
                y:5
                width:68
                height:19
                color:"#ffffffff"
                wrapMode: TextEdit.WordWrap
                text:"#B0D1D8"
                font.family: "Luxi Sans"
                font.italic: false
                font.letterSpacing: 0
                font.pixelSize: 16
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignLeft
                verticalAlignment: Text.AlignTop
            }
            Text {
                id: figma_424_980
                objectName:"Theme_1_4_50%"
                x:15
                y:5
                width:119
                height:19
                color:"#ffffffff"
                wrapMode: TextEdit.WordWrap
                text:"Theme_1_4_50%"
                font.family: "Luxi Sans"
                font.italic: false
                font.letterSpacing: 0
                font.pixelSize: 16
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignLeft
                verticalAlignment: Text.AlignTop
            }
        }
    }
}
