//Generated by FigmaQML

import QtGraphicalEffects 1.15
import QtQuick 2.15
import QtQuick.Shapes 1.15
Rectangle {
    id: figma_143_0
    objectName:"Typography"
    x:-4448
    y:0
    width:1048
    height:1428
    color:"#ffb8bdc0"
    clip: true 
    Text {
        id: figma_146_2242
        objectName:"text_operator"
        x:35
        y:151
        width:72
        height:16
        color:"#ff024873"
        wrapMode: TextEdit.WordWrap
        text:"Body_1"
        font.family: "Luxi Sans"
        font.italic: false
        font.letterSpacing: 0
        font.pixelSize: 10
        font.weight: Font.Normal
        horizontalAlignment: Text.AlignLeft
        verticalAlignment: Text.AlignVCenter
    }
    Text {
        id: figma_146_2413
        objectName:"text_operator"
        x:35
        y:240
        width:72
        height:16
        color:"#ff024873"
        wrapMode: TextEdit.WordWrap
        text:"Body_2"
        font.family: "Luxi Sans"
        font.italic: false
        font.letterSpacing: 0
        font.pixelSize: 10
        font.weight: Font.Normal
        horizontalAlignment: Text.AlignLeft
        verticalAlignment: Text.AlignVCenter
    }
    Text {
        id: figma_424_22
        objectName:"text_operator"
        x:35
        y:333
        width:72
        height:16
        color:"#ff024873"
        wrapMode: TextEdit.WordWrap
        text:"Button"
        font.family: "Luxi Sans"
        font.italic: false
        font.letterSpacing: 0
        font.pixelSize: 10
        font.weight: Font.Normal
        horizontalAlignment: Text.AlignLeft
        verticalAlignment: Text.AlignVCenter
    }
    Text {
        id: figma_424_25
        objectName:"Open Sans Semibold 24/30 1px"
        x:150
        y:329
        width:417
        height:30
        color:"#ff024873"
        wrapMode: TextEdit.WordWrap
        text:"Open Sans Semibold 24/30 1px"
        font.family: "Luxi Sans"
        font.italic: false
        font.letterSpacing: 1
        font.pixelSize: 24
        font.weight: Font.Normal
        horizontalAlignment: Text.AlignLeft
        verticalAlignment: Text.AlignTop
    }
    Text {
        id: figma_501_601
        objectName:"Open Sans Semibold 50/60 0.5px"
        x:150
        y:129
        width:850
        height:60
        color:"#ff024873"
        wrapMode: TextEdit.WordWrap
        text:"Open Sans Semibold 50/60 0.5px"
        font.family: "Luxi Sans"
        font.italic: false
        font.letterSpacing: 0.5
        font.pixelSize: 50
        font.weight: Font.Normal
        horizontalAlignment: Text.AlignLeft
        verticalAlignment: Text.AlignVCenter
    }
    Text {
        id: figma_501_602
        objectName:"Open Sans Semibold 20/30 0.5px"
        x:150
        y:233
        width:422
        height:30
        color:"#ff024873"
        wrapMode: TextEdit.WordWrap
        text:"Open Sans Semibold 20/30 0.5px"
        font.family: "Luxi Sans"
        font.italic: false
        font.letterSpacing: 0.5
        font.pixelSize: 20
        font.weight: Font.Normal
        horizontalAlignment: Text.AlignLeft
        verticalAlignment: Text.AlignVCenter
    }
}
