//Generated by FigmaQML

import QtGraphicalEffects 1.15
import QtQuick 2.15
import QtQuick.Shapes 1.15
Rectangle {
    id: figma_401_4378
    objectName:"Calculator"
    x:-1320
    y:0
    width:360
    height:640
    color: "transparent"
    clip: true 
    Shape {
        id: figma_401_4452
        objectName:"back"
        x:0
        y:24
        width:360
        height:616
        ShapePath {
            strokeColor: "transparent"
            strokeWidth:1
            fillColor:"#ffffffff"
            id: svgpath_figma_401_4452
            fillRule: ShapePath.WindingFill
            PathSvg {
                path: "M0 0L360 0L360 616L0 616L0 0Z"
            } 
        }
    }
    Shape {
        id: figma_401_4453
        objectName:"back_Calculator"
        x:0
        y:24
        width:360
        height:616
        ShapePath {
            strokeColor: "transparent"
            strokeWidth:1
            fillColor:"#ff024873"
            id: svgpath_figma_401_4453
            fillRule: ShapePath.WindingFill
            PathSvg {
                path: "M0 0L360 0L360 616L0 616L0 0Z"
            } 
        }
    }
    Status_bar_figma {
        id: figma_401_4454
        objectName:"Status bar"
        x:0
        y:0
        delegate_15_188:        Rectangle {
            id: figma_i401_4454_15_188
            objectName:"status bar contents"
            x:242
            y:0
            width:118
            height:24
            color:"#00ffffff"
            clip: false 
            Shape {
                id: figma_i401_4454_15_189
                objectName:"bounds"
                x:0
                y:0
                width:118
                height:24
                ShapePath {
                    strokeColor: "transparent"
                    strokeWidth:0
                    fillColor:"transparent"
                    id: svgpath_figma_i401_4454_15_189
                }
            }
            Rectangle {
                id: figma_i401_4454_15_190
                objectName:"time"
                opacity: 0.9
                x:74
                y:3
                width:36
                height:17
                color:"#00ffffff"
                clip: false 
                Text {
                    id: figma_i401_4454_15_191
                    objectName:"12:30"
                    x:0
                    y:0
                    width:36
                    height:17
                    color:"#ffffffff"
                    wrapMode: TextEdit.WordWrap
                    text:"12:30"
                    font.family: "Luxi Sans"
                    font.italic: false
                    font.letterSpacing: 0
                    font.pixelSize: 14
                    font.weight: Font.Normal
                    horizontalAlignment: Text.AlignRight
                    verticalAlignment: Text.AlignBottom
                }
            }
            Rectangle {
                id: figma_i401_4454_15_192
                objectName:"battery"
                x:55
                y:4
                width:16
                height:16
                color:"#00ffffff"
                clip: false 
                Shape {
                    id: figma_i401_4454_15_193
                    objectName:"bounds"
                    x:0
                    y:0
                    width:16
                    height:16
                    ShapePath {
                        strokeColor: "transparent"
                        strokeWidth:0
                        fillColor:"transparent"
                        id: svgpath_figma_i401_4454_15_193
                    }
                }
                Shape {
                    id: figma_i401_4454_15_194
                    objectName:"Shape"
                    x:3
                    y:1
                    width:9
                    height:14
                    ShapePath {
                        strokeColor: "transparent"
                        strokeWidth:0
                        fillColor:"#ffffffff"
                        id: svgpath_figma_i401_4454_15_194
                        PathSvg {
                            path: "M6 0.875L6 3.77476e-15L3 1.11022e-16L3 0.875L0 0.875L0 14L9 14L9 0.875L6 0.875Z"
                        } 
                    }
                }
            }
            Rectangle {
                id: figma_i401_4454_15_195
                objectName:"cellular"
                x:35
                y:4
                width:16
                height:16
                color:"#00ffffff"
                clip: false 
                Shape {
                    id: figma_i401_4454_15_196
                    objectName:"bounds"
                    x:0
                    y:0
                    width:16
                    height:16
                    ShapePath {
                        strokeColor: "transparent"
                        strokeWidth:0
                        fillColor:"transparent"
                        id: svgpath_figma_i401_4454_15_196
                    }
                }
                Shape {
                    id: figma_i401_4454_15_197
                    objectName:"Shape"
                    x:0
                    y:1
                    width:14
                    height:14
                    ShapePath {
                        strokeColor: "transparent"
                        strokeWidth:0
                        fillColor:"#ffffffff"
                        id: svgpath_figma_i401_4454_15_197
                        PathSvg {
                            path: "M0 14L14 14L14 0L0 14Z"
                        } 
                    }
                }
            }
            Rectangle {
                id: figma_i401_4454_15_198
                objectName:"wifi"
                x:14
                y:4
                width:18.0453
                height:16
                color:"#00ffffff"
                clip: false 
                Shape {
                    id: figma_i401_4454_15_199
                    objectName:"bounds"
                    x:1
                    y:0
                    width:16
                    height:16
                    ShapePath {
                        strokeColor: "transparent"
                        strokeWidth:0
                        fillColor:"transparent"
                        id: svgpath_figma_i401_4454_15_199
                    }
                }
                Shape {
                    id: figma_i401_4454_15_200
                    objectName:"Shape"
                    x:0
                    y:1
                    width:18.0453
                    height:14
                    ShapePath {
                        strokeColor: "transparent"
                        strokeWidth:0
                        fillColor:"#ffffffff"
                        id: svgpath_figma_i401_4454_15_200
                        PathSvg {
                            path: "M0 3.01593L9.02263 14L18.0453 3.01593C15.5344 1.12256 12.4096 0 9.02263 0C5.63564 0 2.51085 1.12256 0 3.01593Z"
                        } 
                    }
                }
            }
        }
    }
    Shape {
        id: figma_501_152
        objectName:"back_calculation"
        x:0
        y:24
        width:360
        height:156
        ShapePath {
            strokeColor: "transparent"
            strokeWidth:1
            fillColor:"#ff04bfad"
            id: svgpath_figma_501_152
            fillRule: ShapePath.WindingFill
            PathSvg {
                path: "M0 0L360 0L360 126C360 142.569 346.569 156 330 156L30 156C13.4315 156 0 142.569 0 126L0 0Z"
            } 
        }
    }
    Rectangle {
        id: figma_501_606
        objectName:"result"
        x:39
        y:106
        width:281
        height:60
        color: "transparent"
        clip: false 
        Shape {
            id: figma_501_605
            objectName:"back_result"
            x:0
            y:0
            width:281
            height:60
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1
                fillColor:"transparent"
                id: svgpath_figma_501_605
            }
        }
        Text {
            id: figma_501_592
            objectName:"text_result"
            x:0
            y:0
            width:281
            height:60
            color:"#ffffffff"
            wrapMode: TextEdit.WordWrap
            text:"0"
            font.family: "Luxi Sans"
            font.italic: false
            font.letterSpacing: 0.5
            font.pixelSize: 50
            font.weight: Font.Normal
            horizontalAlignment: Text.AlignRight
            verticalAlignment: Text.AlignVCenter
        }
    }
    Rectangle {
        id: figma_501_604
        objectName:"calculation line"
        visible: false
        x:39
        y:68
        width:280
        height:30
        color: "transparent"
        clip: false 
        Shape {
            id: figma_501_603
            objectName:"back_calculation line"
            x:0
            y:0
            width:280
            height:30
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:1
                fillColor:"transparent"
                id: svgpath_figma_501_603
            }
        }
        Text {
            id: figma_501_595
            objectName:"text_calculation line"
            x:0
            y:0
            width:280
            height:30
            color:"#ffffffff"
            wrapMode: TextEdit.WordWrap
            text:"12+1552"
            font.family: "Luxi Sans"
            font.italic: false
            font.letterSpacing: 0.5
            font.pixelSize: 20
            font.weight: Font.Normal
            horizontalAlignment: Text.AlignRight
            verticalAlignment: Text.AlignVCenter
        }
    }
    Button_cancel_normal_figma {
        id: figma_501_243
        objectName:"button/cancel/normal"
        x:24
        y:540
    }
    Rectangle {
        id: figma_501_588
        objectName:"button_simple"
        x:24
        y:288
        width:228
        height:312
        color: "transparent"
        clip: false 
        Button_simple_normal_figma {
            id: figma_501_262
            objectName:"button/simple/normal"
            x:0
            y:168
            delegate_501_187:            Text {
                id: figma_i501_262_501_187
                objectName:"text_button"
                x:15
                y:15
                width:30
                height:30
                color:"#ff024873"
                wrapMode: TextEdit.WordWrap
                text:"1"
                font.family: "Luxi Sans"
                font.italic: false
                font.letterSpacing: 1
                font.pixelSize: 24
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignHCenter
                verticalAlignment: Text.AlignBottom
            }
        }
        Button_simple_normal_figma {
            id: figma_501_265
            objectName:"button/simple/normal"
            x:0
            y:84
            delegate_501_187:            Text {
                id: figma_i501_265_501_187
                objectName:"text_button"
                x:15
                y:15
                width:30
                height:30
                color:"#ff024873"
                wrapMode: TextEdit.WordWrap
                text:"4"
                font.family: "Luxi Sans"
                font.italic: false
                font.letterSpacing: 1
                font.pixelSize: 24
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignHCenter
                verticalAlignment: Text.AlignBottom
            }
        }
        Button_simple_normal_figma {
            id: figma_501_268
            objectName:"button/simple/normal"
            x:0
            y:0
            delegate_501_187:            Text {
                id: figma_i501_268_501_187
                objectName:"text_button"
                x:15
                y:15
                width:30
                height:30
                color:"#ff024873"
                wrapMode: TextEdit.WordWrap
                text:"7"
                font.family: "Luxi Sans"
                font.italic: false
                font.letterSpacing: 1
                font.pixelSize: 24
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignHCenter
                verticalAlignment: Text.AlignBottom
            }
        }
        Button_simple_normal_figma {
            id: figma_501_246
            objectName:"button/simple/normal"
            x:84
            y:252
            delegate_501_187:            Text {
                id: figma_i501_246_501_187
                objectName:"text_button"
                x:15
                y:15
                width:30
                height:30
                color:"#ff024873"
                wrapMode: TextEdit.WordWrap
                text:"0"
                font.family: "Luxi Sans"
                font.italic: false
                font.letterSpacing: 1
                font.pixelSize: 24
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignHCenter
                verticalAlignment: Text.AlignBottom
            }
        }
        Button_simple_normal_figma {
            id: figma_501_280
            objectName:"button/simple/normal"
            x:84
            y:168
        }
        Button_simple_normal_figma {
            id: figma_501_358
            objectName:"button/simple/normal"
            x:84
            y:84
            delegate_501_187:            Text {
                id: figma_i501_358_501_187
                objectName:"text_button"
                x:15
                y:15
                width:30
                height:30
                color:"#ff024873"
                wrapMode: TextEdit.WordWrap
                text:"5"
                font.family: "Luxi Sans"
                font.italic: false
                font.letterSpacing: 1
                font.pixelSize: 24
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignHCenter
                verticalAlignment: Text.AlignBottom
            }
        }
        Button_simple_normal_figma {
            id: figma_501_364
            objectName:"button/simple/normal"
            x:84
            y:0
            delegate_501_187:            Text {
                id: figma_i501_364_501_187
                objectName:"text_button"
                x:15
                y:15
                width:30
                height:30
                color:"#ff024873"
                wrapMode: TextEdit.WordWrap
                text:"8"
                font.family: "Luxi Sans"
                font.italic: false
                font.letterSpacing: 1
                font.pixelSize: 24
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignHCenter
                verticalAlignment: Text.AlignBottom
            }
        }
        Button_simple_normal_figma {
            id: figma_501_249
            objectName:"button/simple/normal"
            x:168
            y:252
            delegate_501_187:            Text {
                id: figma_i501_249_501_187
                objectName:"text_button"
                x:15
                y:15
                width:30
                height:30
                color:"#ff024873"
                wrapMode: TextEdit.WordWrap
                text:"."
                font.family: "Luxi Sans"
                font.italic: false
                font.letterSpacing: 1
                font.pixelSize: 24
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignHCenter
                verticalAlignment: Text.AlignBottom
            }
        }
        Button_simple_normal_figma {
            id: figma_501_281
            objectName:"button/simple/normal"
            x:168
            y:168
            delegate_501_187:            Text {
                id: figma_i501_281_501_187
                objectName:"text_button"
                x:15
                y:15
                width:30
                height:30
                color:"#ff024873"
                wrapMode: TextEdit.WordWrap
                text:"3"
                font.family: "Luxi Sans"
                font.italic: false
                font.letterSpacing: 1
                font.pixelSize: 24
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignHCenter
                verticalAlignment: Text.AlignBottom
            }
        }
        Button_simple_normal_figma {
            id: figma_501_359
            objectName:"button/simple/normal"
            x:168
            y:84
            delegate_501_187:            Text {
                id: figma_i501_359_501_187
                objectName:"text_button"
                x:15
                y:15
                width:30
                height:30
                color:"#ff024873"
                wrapMode: TextEdit.WordWrap
                text:"6"
                font.family: "Luxi Sans"
                font.italic: false
                font.letterSpacing: 1
                font.pixelSize: 24
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignHCenter
                verticalAlignment: Text.AlignBottom
            }
        }
        Button_simple_normal_figma {
            id: figma_501_365
            objectName:"button/simple/normal"
            x:168
            y:0
            delegate_501_187:            Text {
                id: figma_i501_365_501_187
                objectName:"text_button"
                x:15
                y:15
                width:30
                height:30
                color:"#ff024873"
                wrapMode: TextEdit.WordWrap
                text:"9"
                font.family: "Luxi Sans"
                font.italic: false
                font.letterSpacing: 1
                font.pixelSize: 24
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignHCenter
                verticalAlignment: Text.AlignBottom
            }
        }
    }
    Rectangle {
        id: figma_501_589
        objectName:"button_action"
        x:24
        y:204
        width:312
        height:396
        color: "transparent"
        clip: false 
        Button_action_normal_figma {
            id: figma_501_271
            objectName:"button/action/normal"
            x:0
            y:0
            delegate_501_222:            Icon_30_bkt_figma {
                id: figma_i501_271_501_222
                objectName:"icon/30/bkt"
                x:15
                y:15
            }
        }
        Button_action_normal_figma {
            id: figma_501_402
            objectName:"button/action/normal"
            x:84
            y:0
            delegate_501_222:            Icon_30_plus_minus_figma {
                id: figma_i501_402_501_222
                objectName:"icon/30/plus_minus"
                x:15
                y:15
                delegate_501_550:                Rectangle {
                    id: figma_i501_402_501_222_501_550
                    objectName:"plus_minus"
                    x:4
                    y:7
                    width:22
                    height:16
                    color: "transparent"
                    clip: false 
                    Shape {
                        id: figma_i501_402_501_222_501_551
                        objectName:"Vector 177"
                        x:8
                        y:0
                        width:6
                        height:16
                        ShapePath {
                            joinStyle: ShapePath.MiterJoin
                            strokeColor: "#ffffffff"
                            strokeWidth:2
                            fillColor:"transparent"
                            id: svgpath_figma_i501_402_501_222_501_551
                            fillRule: ShapePath.WindingFill
                            PathSvg {
                                path: "M6.93633 0.351123C7.13025 -0.165997 6.86824 -0.742409 6.35112 -0.936329C5.834 -1.13025 5.25759 -0.868244 5.06367 -0.351123L6.93633 0.351123ZM-0.936329 15.6489C-1.13025 16.166 -0.868244 16.7424 -0.351123 16.9363C0.165997 17.1302 0.742409 16.8682 0.936329 16.3511L-0.936329 15.6489ZM5.06367 -0.351123L-0.936329 15.6489L0.936329 16.3511L6.93633 0.351123L5.06367 -0.351123Z"
                            } 
                        }
                    }
                    Rectangle {
                        id: figma_i501_402_501_222_501_556
                        objectName:"plus"
                        x:0
                        y:0
                        width:8
                        height:8
                        color: "transparent"
                        clip: false 
                        Shape {
                            id: figma_i501_402_501_222_501_554
                            objectName:"Vector 178"
                            x:4
                            y:0
                            width:0
                            height:8
                            ShapePath {
                                joinStyle: ShapePath.MiterJoin
                                strokeColor: "#ffffffff"
                                strokeWidth:2
                                fillColor:"transparent"
                                id: svgpath_figma_i501_402_501_222_501_554
                                fillRule: ShapePath.WindingFill
                                PathSvg {
                                    path: "M1 0C1 -0.552285 0.552285 -1 0 -1C-0.552285 -1 -1 -0.552285 -1 0L1 0ZM-1 8C-1 8.55229 -0.552285 9 0 9C0.552285 9 1 8.55229 1 8L-1 8ZM-1 0L-1 8L1 8L1 0L-1 0Z"
                                } 
                            }
                        }
                        Shape {
                            id: figma_i501_402_501_222_501_555
                            objectName:"Vector 179"
                            transform: Matrix4x4 {
                                matrix: Qt.matrix4x4(
                                -4.37114e-08, -1, 8, 0,
                                1, -4.37114e-08, 4, 0,
                                0, 0, 1, 0,
                                0, 0, 0, 1)
                            }
                            x:8
                            y:4
                            width:0
                            height:8
                            ShapePath {
                                joinStyle: ShapePath.MiterJoin
                                strokeColor: "#ffffffff"
                                strokeWidth:2
                                fillColor:"transparent"
                                id: svgpath_figma_i501_402_501_222_501_555
                                fillRule: ShapePath.WindingFill
                                PathSvg {
                                    path: "M1 0C1 -0.552285 0.552285 -1 0 -1C-0.552285 -1 -1 -0.552285 -1 0L1 0ZM-1 8C-1 8.55229 -0.552285 9 0 9C0.552285 9 1 8.55229 1 8L-1 8ZM-1 0L-1 8L1 8L1 0L-1 0Z"
                                } 
                            }
                        }
                    }
                    Shape {
                        id: figma_i501_402_501_222_501_557
                        objectName:"minus"
                        transform: Matrix4x4 {
                            matrix: Qt.matrix4x4(
                            -4.37114e-08, -1, 22, 0,
                            1, -4.37114e-08, 12, 0,
                            0, 0, 1, 0,
                            0, 0, 0, 1)
                        }
                        x:22
                        y:12
                        width:0
                        height:8
                        ShapePath {
                            joinStyle: ShapePath.MiterJoin
                            strokeColor: "#ffffffff"
                            strokeWidth:2
                            fillColor:"transparent"
                            id: svgpath_figma_i501_402_501_222_501_557
                            fillRule: ShapePath.WindingFill
                            PathSvg {
                                path: "M1 0C1 -0.552285 0.552285 -1 0 -1C-0.552285 -1 -1 -0.552285 -1 0L1 0ZM-1 8C-1 8.55229 -0.552285 9 0 9C0.552285 9 1 8.55229 1 8L-1 8ZM-1 0L-1 8L1 8L1 0L-1 0Z"
                            } 
                        }
                    }
                }
            }
        }
        Button_action_normal_figma {
            id: figma_501_409
            objectName:"button/action/normal"
            x:168
            y:0
            delegate_501_222:            Icon_30_percent_figma {
                id: figma_i501_409_501_222
                objectName:"icon/30/percent"
                x:15
                y:15
                delegate_501_536:                Rectangle {
                    id: figma_i501_409_501_222_501_536
                    objectName:"percent"
                    x:6
                    y:6
                    width:18
                    height:18
                    color: "transparent"
                    clip: false 
                    Shape {
                        id: figma_i501_409_501_222_501_515
                        objectName:"Vector 177"
                        x:4
                        y:1
                        width:10
                        height:16
                        ShapePath {
                            joinStyle: ShapePath.MiterJoin
                            strokeColor: "#ffffffff"
                            strokeWidth:2
                            fillColor:"transparent"
                            id: svgpath_figma_i501_409_501_222_501_515
                            fillRule: ShapePath.WindingFill
                            PathSvg {
                                path: "M10.848 0.529999C11.1407 0.0616624 10.9983 -0.555288 10.53 -0.847998C10.0617 -1.14071 9.44471 -0.998335 9.152 -0.529999L10.848 0.529999ZM-0.847998 15.47C-1.14071 15.9383 -0.998335 16.5553 -0.529999 16.848C-0.0616624 17.1407 0.555288 16.9983 0.847998 16.53L-0.847998 15.47ZM9.152 -0.529999L-0.847998 15.47L0.847998 16.53L10.848 0.529999L9.152 -0.529999Z"
                            } 
                        }
                    }
                    Shape {
                        id: figma_i501_409_501_222_501_521
                        objectName:"Ellipse 278"
                        x:12
                        y:10
                        width:6
                        height:8
                        ShapePath {
                            joinStyle: ShapePath.MiterJoin
                            strokeColor: "#ffffffff"
                            strokeWidth:2
                            fillColor:"transparent"
                            id: svgpath_figma_i501_409_501_222_501_521
                            fillRule: ShapePath.WindingFill
                            PathSvg {
                                path: "M5 4C5 4.90912 4.72237 5.69369 4.32132 6.22843C3.9205 6.76286 3.4431 7 3 7L3 9C4.21375 9 5.23636 8.34171 5.92132 7.42843C6.60605 6.51545 7 5.30002 7 4L5 4ZM3 7C2.5569 7 2.0795 6.76286 1.67868 6.22843C1.27762 5.69369 1 4.90912 1 4L-1 4C-1 5.30002 -0.606052 6.51545 0.0786797 7.42843C0.763642 8.34171 1.78625 9 3 9L3 7ZM1 4C1 3.09088 1.27762 2.30631 1.67868 1.77157C2.0795 1.23714 2.5569 1 3 1L3 -1C1.78625 -1 0.763642 -0.34171 0.0786797 0.571573C-0.606052 1.48455 -1 2.69998 -1 4L1 4ZM3 1C3.4431 1 3.9205 1.23714 4.32132 1.77157C4.72237 2.30631 5 3.09088 5 4L7 4C7 2.69998 6.60605 1.48455 5.92132 0.571573C5.23636 -0.34171 4.21375 -1 3 -1L3 1Z"
                            } 
                        }
                    }
                    Shape {
                        id: figma_i501_409_501_222_501_526
                        objectName:"Ellipse 279"
                        x:0
                        y:0
                        width:6
                        height:8
                        ShapePath {
                            joinStyle: ShapePath.MiterJoin
                            strokeColor: "#ffffffff"
                            strokeWidth:2
                            fillColor:"transparent"
                            id: svgpath_figma_i501_409_501_222_501_526
                            fillRule: ShapePath.WindingFill
                            PathSvg {
                                path: "M5 4C5 4.90912 4.72237 5.69369 4.32132 6.22843C3.9205 6.76286 3.4431 7 3 7L3 9C4.21375 9 5.23636 8.34171 5.92132 7.42843C6.60605 6.51545 7 5.30002 7 4L5 4ZM3 7C2.5569 7 2.0795 6.76286 1.67868 6.22843C1.27762 5.69369 1 4.90912 1 4L-1 4C-1 5.30002 -0.606052 6.51545 0.0786797 7.42843C0.763642 8.34171 1.78625 9 3 9L3 7ZM1 4C1 3.09088 1.27762 2.30631 1.67868 1.77157C2.0795 1.23714 2.5569 1 3 1L3 -1C1.78625 -1 0.763642 -0.34171 0.0786797 0.571573C-0.606052 1.48455 -1 2.69998 -1 4L1 4ZM3 1C3.4431 1 3.9205 1.23714 4.32132 1.77157C4.72237 2.30631 5 3.09088 5 4L7 4C7 2.69998 6.60605 1.48455 5.92132 0.571573C5.23636 -0.34171 4.21375 -1 3 -1L3 1Z"
                            } 
                        }
                    }
                }
            }
        }
        Button_action_normal_figma {
            id: figma_501_252
            objectName:"button/action/normal"
            x:252
            y:336
            delegate_501_222:            Icon_30_equal_figma {
                id: figma_i501_252_501_222
                objectName:"icon/30/equal"
                x:15
                y:15
            }
        }
        Button_action_normal_figma {
            id: figma_501_370
            objectName:"button/action/normal"
            x:252
            y:252
            delegate_501_222:            Icon_30_plus_figma {
                id: figma_i501_370_501_222
                objectName:"icon/30/plus"
                x:15
                y:15
                delegate_501_219:                Rectangle {
                    id: figma_i501_370_501_222_501_219
                    objectName:"plus"
                    x:5
                    y:5
                    width:19
                    height:19
                    color: "transparent"
                    clip: false 
                    Shape {
                        id: figma_i501_370_501_222_501_214
                        objectName:"Vector 175"
                        x:9
                        y:0
                        width:0
                        height:19
                        ShapePath {
                            joinStyle: ShapePath.MiterJoin
                            strokeColor: "#ffffffff"
                            strokeWidth:2
                            fillColor:"transparent"
                            id: svgpath_figma_i501_370_501_222_501_214
                            fillRule: ShapePath.WindingFill
                            PathSvg {
                                path: "M1 0C1 -0.552285 0.552285 -1 0 -1C-0.552285 -1 -1 -0.552285 -1 0L1 0ZM-1 19C-1 19.5523 -0.552285 20 0 20C0.552285 20 1 19.5523 1 19L-1 19ZM-1 0L-1 19L1 19L1 0L-1 0Z"
                            } 
                        }
                    }
                    Shape {
                        id: figma_i501_370_501_222_501_218
                        objectName:"Vector 176"
                        transform: Matrix4x4 {
                            matrix: Qt.matrix4x4(
                            -4.37114e-08, -1, 19, 0,
                            1, -4.37114e-08, 9.5, 0,
                            0, 0, 1, 0,
                            0, 0, 0, 1)
                        }
                        x:19
                        y:9
                        width:0
                        height:19
                        ShapePath {
                            joinStyle: ShapePath.MiterJoin
                            strokeColor: "#ffffffff"
                            strokeWidth:2
                            fillColor:"transparent"
                            id: svgpath_figma_i501_370_501_222_501_218
                            fillRule: ShapePath.WindingFill
                            PathSvg {
                                path: "M1 0C1 -0.552285 0.552285 -1 0 -1C-0.552285 -1 -1 -0.552285 -1 0L1 0ZM-1 19C-1 19.5523 -0.552285 20 0 20C0.552285 20 1 19.5523 1 19L-1 19ZM-1 0L-1 19L1 19L1 0L-1 0Z"
                            } 
                        }
                    }
                }
            }
        }
        Button_action_normal_figma {
            id: figma_501_377
            objectName:"button/action/normal"
            x:252
            y:168
            delegate_501_222:            Icon_30_minus_figma {
                id: figma_i501_377_501_222
                objectName:"icon/30/minus"
                x:15
                y:15
            }
        }
        Button_action_normal_figma {
            id: figma_501_384
            objectName:"button/action/normal"
            x:252
            y:84
            delegate_501_222:            Icon_30_multiplication_figma {
                id: figma_i501_384_501_222
                objectName:"icon/30/multiplication"
                x:15
                y:15
                delegate_501_457:                Rectangle {
                    id: figma_i501_384_501_222_501_457
                    objectName:"multiplication"
                    transform: Matrix4x4 {
                        matrix: Qt.matrix4x4(
                        0.707107, -0.707107, 15, 0,
                        0.707107, 0.707107, 1.56497, 0,
                        0, 0, 1, 0,
                        0, 0, 0, 1)
                    }
                    x:15
                    y:1
                    width:19
                    height:19
                    color: "transparent"
                    clip: false 
                    Shape {
                        id: figma_i501_384_501_222_501_458
                        objectName:"Vector 175"
                        x:9
                        y:0
                        width:0
                        height:19
                        ShapePath {
                            joinStyle: ShapePath.MiterJoin
                            strokeColor: "#ffffffff"
                            strokeWidth:2
                            fillColor:"transparent"
                            id: svgpath_figma_i501_384_501_222_501_458
                            fillRule: ShapePath.WindingFill
                            PathSvg {
                                path: "M1 0C1 -0.552285 0.552285 -1 0 -1C-0.552285 -1 -1 -0.552285 -1 0L1 0ZM-1 19C-1 19.5523 -0.552285 20 0 20C0.552285 20 1 19.5523 1 19L-1 19ZM-1 0L-1 19L1 19L1 0L-1 0Z"
                            } 
                        }
                    }
                    Shape {
                        id: figma_i501_384_501_222_501_459
                        objectName:"Vector 176"
                        transform: Matrix4x4 {
                            matrix: Qt.matrix4x4(
                            -4.37114e-08, -1, 19, 0,
                            1, -4.37114e-08, 9.5, 0,
                            0, 0, 1, 0,
                            0, 0, 0, 1)
                        }
                        x:19
                        y:9
                        width:0
                        height:19
                        ShapePath {
                            joinStyle: ShapePath.MiterJoin
                            strokeColor: "#ffffffff"
                            strokeWidth:2
                            fillColor:"transparent"
                            id: svgpath_figma_i501_384_501_222_501_459
                            fillRule: ShapePath.WindingFill
                            PathSvg {
                                path: "M1 0C1 -0.552285 0.552285 -1 0 -1C-0.552285 -1 -1 -0.552285 -1 0L1 0ZM-1 19C-1 19.5523 -0.552285 20 0 20C0.552285 20 1 19.5523 1 19L-1 19ZM-1 0L-1 19L1 19L1 0L-1 0Z"
                            } 
                        }
                    }
                }
            }
        }
        Button_action_normal_figma {
            id: figma_501_391
            objectName:"button/action/normal"
            x:252
            y:0
            delegate_501_222:            Icon_30_division_figma {
                id: figma_i501_391_501_222
                objectName:"icon/30/division"
                x:15
                y:15
                delegate_501_488:                Rectangle {
                    id: figma_i501_391_501_222_501_488
                    objectName:"division"
                    x:5
                    y:6
                    width:19
                    height:18
                    color: "transparent"
                    clip: false 
                    Shape {
                        id: figma_i501_391_501_222_501_472
                        objectName:"minus"
                        transform: Matrix4x4 {
                            matrix: Qt.matrix4x4(
                            -4.37114e-08, -1, 19, 0,
                            1, -4.37114e-08, 9, 0,
                            0, 0, 1, 0,
                            0, 0, 0, 1)
                        }
                        x:19
                        y:9
                        width:0
                        height:19
                        ShapePath {
                            joinStyle: ShapePath.MiterJoin
                            strokeColor: "#ffffffff"
                            strokeWidth:2
                            fillColor:"transparent"
                            id: svgpath_figma_i501_391_501_222_501_472
                            fillRule: ShapePath.WindingFill
                            PathSvg {
                                path: "M1 0C1 -0.552285 0.552285 -1 0 -1C-0.552285 -1 -1 -0.552285 -1 0L1 0ZM-1 19C-1 19.5523 -0.552285 20 0 20C0.552285 20 1 19.5523 1 19L-1 19ZM-1 0L-1 19L1 19L1 0L-1 0Z"
                            } 
                        }
                    }
                    Shape {
                        id: figma_i501_391_501_222_501_473
                        objectName:"Ellipse 276"
                        x:7
                        y:0
                        width:4
                        height:4
                        ShapePath {
                            strokeColor: "transparent"
                            strokeWidth:1
                            fillColor:"#ffffffff"
                            id: svgpath_figma_i501_391_501_222_501_473
                            fillRule: ShapePath.WindingFill
                            PathSvg {
                                path: "M4 2C4 3.10457 3.10457 4 2 4C0.895431 4 0 3.10457 0 2C0 0.895431 0.895431 0 2 0C3.10457 0 4 0.895431 4 2Z"
                            } 
                        }
                    }
                    Shape {
                        id: figma_i501_391_501_222_501_474
                        objectName:"Ellipse 277"
                        x:7
                        y:14
                        width:4
                        height:4
                        ShapePath {
                            strokeColor: "transparent"
                            strokeWidth:1
                            fillColor:"#ffffffff"
                            id: svgpath_figma_i501_391_501_222_501_474
                            fillRule: ShapePath.WindingFill
                            PathSvg {
                                path: "M4 2C4 3.10457 3.10457 4 2 4C0.895431 4 0 3.10457 0 2C0 0.895431 0.895431 0 2 0C3.10457 0 4 0.895431 4 2Z"
                            } 
                        }
                    }
                }
            }
        }
    }
}
