//Generated by FigmaQML

import QtGraphicalEffects 1.15
import QtQuick 2.15
import QtQuick.Shapes 1.15
Rectangle {
    id: figma_15_186
    objectName:"Status bar"
    x:15
    y:11
    width:360
    height:24
    color: "transparent"
    clip: false 
    property Component delegate_15_187:     Shape {
        id: figma_15_187
        objectName:"status bar bg"
        x:0
        y:0
        width:360
        height:24
        ShapePath {
            strokeColor: "transparent"
            strokeWidth:0
            fillColor:"#ff04bfad"
            id: svgpath_figma_15_187
            PathSvg {
                path: "M0 0L0 24L360 24L360 0L0 0Z"
            } 
        }
    }
    property Item i_delegate_15_187
    property matrix4x4 delegate_15_187_transform: Qt.matrix4x4(Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,)
    onDelegate_15_187_transformChanged: {if(i_delegate_15_187 && i_delegate_15_187.transform != delegate_15_187_transform) i_delegate_15_187.transform = delegate_15_187_transform;}
    property real delegate_15_187_x: NaN
    onDelegate_15_187_xChanged: {if(i_delegate_15_187 && i_delegate_15_187.x != delegate_15_187_x) i_delegate_15_187.x = delegate_15_187_x;}
    property real delegate_15_187_y: NaN
    onDelegate_15_187_yChanged: {if(i_delegate_15_187 && i_delegate_15_187.y != delegate_15_187_y) i_delegate_15_187.y = delegate_15_187_y;}
    property real delegate_15_187_width: NaN
    onDelegate_15_187_widthChanged: {if(i_delegate_15_187 && i_delegate_15_187.width != delegate_15_187_width) i_delegate_15_187.width = delegate_15_187_width;}
    property real delegate_15_187_height: NaN
    onDelegate_15_187_heightChanged: {if(i_delegate_15_187 && i_delegate_15_187.height != delegate_15_187_height) i_delegate_15_187.height = delegate_15_187_height;}
    property Component delegate_15_188:     Rectangle {
        id: figma_15_188
        objectName:"status bar contents"
        x:242
        y:0
        width:118
        height:24
        color:"#00ffffff"
        clip: false 
        Shape {
            id: figma_15_189
            objectName:"bounds"
            x:0
            y:0
            width:118
            height:24
            ShapePath {
                strokeColor: "transparent"
                strokeWidth:0
                fillColor:"transparent"
                id: svgpath_figma_15_189
            }
        }
        Rectangle {
            id: figma_15_190
            objectName:"time"
            opacity: 0.9
            x:74
            y:3
            width:36
            height:17
            color:"#00ffffff"
            clip: false 
            Text {
                id: figma_15_191
                objectName:"12:30"
                x:0
                y:0
                width:36
                height:17
                color:"#ffffffff"
                wrapMode: TextEdit.WordWrap
                text:"12:30"
                font.family: "Luxi Sans"
                font.italic: false
                font.letterSpacing: 0
                font.pixelSize: 14
                font.weight: Font.Normal
                horizontalAlignment: Text.AlignRight
                verticalAlignment: Text.AlignBottom
            }
        }
        Rectangle {
            id: figma_15_192
            objectName:"battery"
            x:55
            y:4
            width:16
            height:16
            color:"#00ffffff"
            clip: false 
            Shape {
                id: figma_15_193
                objectName:"bounds"
                x:0
                y:0
                width:16
                height:16
                ShapePath {
                    strokeColor: "transparent"
                    strokeWidth:0
                    fillColor:"transparent"
                    id: svgpath_figma_15_193
                }
            }
            Shape {
                id: figma_15_194
                objectName:"Shape"
                x:3
                y:1
                width:9
                height:14
                ShapePath {
                    strokeColor: "transparent"
                    strokeWidth:0
                    fillColor:"#ffffffff"
                    id: svgpath_figma_15_194
                    PathSvg {
                        path: "M6 0.875L6 3.77476e-15L3 1.11022e-16L3 0.875L0 0.875L0 14L9 14L9 0.875L6 0.875Z"
                    } 
                }
            }
        }
        Rectangle {
            id: figma_15_195
            objectName:"cellular"
            x:35
            y:4
            width:16
            height:16
            color:"#00ffffff"
            clip: false 
            Shape {
                id: figma_15_196
                objectName:"bounds"
                x:0
                y:0
                width:16
                height:16
                ShapePath {
                    strokeColor: "transparent"
                    strokeWidth:0
                    fillColor:"transparent"
                    id: svgpath_figma_15_196
                }
            }
            Shape {
                id: figma_15_197
                objectName:"Shape"
                x:0
                y:1
                width:14
                height:14
                ShapePath {
                    strokeColor: "transparent"
                    strokeWidth:0
                    fillColor:"#ffffffff"
                    id: svgpath_figma_15_197
                    PathSvg {
                        path: "M0 14L14 14L14 0L0 14Z"
                    } 
                }
            }
        }
        Rectangle {
            id: figma_15_198
            objectName:"wifi"
            x:14
            y:4
            width:18.0453
            height:16
            color:"#00ffffff"
            clip: false 
            Shape {
                id: figma_15_199
                objectName:"bounds"
                x:1
                y:0
                width:16
                height:16
                ShapePath {
                    strokeColor: "transparent"
                    strokeWidth:0
                    fillColor:"transparent"
                    id: svgpath_figma_15_199
                }
            }
            Shape {
                id: figma_15_200
                objectName:"Shape"
                x:0
                y:1
                width:18.0453
                height:14
                ShapePath {
                    strokeColor: "transparent"
                    strokeWidth:0
                    fillColor:"#ffffffff"
                    id: svgpath_figma_15_200
                    PathSvg {
                        path: "M0 3.01593L9.02263 14L18.0453 3.01593C15.5344 1.12256 12.4096 0 9.02263 0C5.63564 0 2.51085 1.12256 0 3.01593Z"
                    } 
                }
            }
        }
    }
    property Item i_delegate_15_188
    property matrix4x4 delegate_15_188_transform: Qt.matrix4x4(Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,)
    onDelegate_15_188_transformChanged: {if(i_delegate_15_188 && i_delegate_15_188.transform != delegate_15_188_transform) i_delegate_15_188.transform = delegate_15_188_transform;}
    property real delegate_15_188_x: NaN
    onDelegate_15_188_xChanged: {if(i_delegate_15_188 && i_delegate_15_188.x != delegate_15_188_x) i_delegate_15_188.x = delegate_15_188_x;}
    property real delegate_15_188_y: NaN
    onDelegate_15_188_yChanged: {if(i_delegate_15_188 && i_delegate_15_188.y != delegate_15_188_y) i_delegate_15_188.y = delegate_15_188_y;}
    property real delegate_15_188_width: NaN
    onDelegate_15_188_widthChanged: {if(i_delegate_15_188 && i_delegate_15_188.width != delegate_15_188_width) i_delegate_15_188.width = delegate_15_188_width;}
    property real delegate_15_188_height: NaN
    onDelegate_15_188_heightChanged: {if(i_delegate_15_188 && i_delegate_15_188.height != delegate_15_188_height) i_delegate_15_188.height = delegate_15_188_height;}
    Component.onCompleted: {
        const o_delegate_15_187 = {}
        if(!isNaN(delegate_15_187_transform.m11)) o_delegate_15_187['transform'] = delegate_15_187_transform;
        if(!isNaN(delegate_15_187_x)) o_delegate_15_187['x'] = delegate_15_187_x;
        if(!isNaN(delegate_15_187_y)) o_delegate_15_187['y'] = delegate_15_187_y;
        if(!isNaN(delegate_15_187_width)) o_delegate_15_187['width'] = delegate_15_187_width;
        if(!isNaN(delegate_15_187_height)) o_delegate_15_187['height'] = delegate_15_187_height;
        i_delegate_15_187 = delegate_15_187.createObject(this, o_delegate_15_187)
        delegate_15_187_x = Qt.binding(()=>i_delegate_15_187.x)
        delegate_15_187_y = Qt.binding(()=>i_delegate_15_187.y)
        delegate_15_187_width = Qt.binding(()=>i_delegate_15_187.width)
        delegate_15_187_height = Qt.binding(()=>i_delegate_15_187.height)
        const o_delegate_15_188 = {}
        if(!isNaN(delegate_15_188_transform.m11)) o_delegate_15_188['transform'] = delegate_15_188_transform;
        if(!isNaN(delegate_15_188_x)) o_delegate_15_188['x'] = delegate_15_188_x;
        if(!isNaN(delegate_15_188_y)) o_delegate_15_188['y'] = delegate_15_188_y;
        if(!isNaN(delegate_15_188_width)) o_delegate_15_188['width'] = delegate_15_188_width;
        if(!isNaN(delegate_15_188_height)) o_delegate_15_188['height'] = delegate_15_188_height;
        i_delegate_15_188 = delegate_15_188.createObject(this, o_delegate_15_188)
        delegate_15_188_x = Qt.binding(()=>i_delegate_15_188.x)
        delegate_15_188_y = Qt.binding(()=>i_delegate_15_188.y)
        delegate_15_188_width = Qt.binding(()=>i_delegate_15_188.width)
        delegate_15_188_height = Qt.binding(()=>i_delegate_15_188.height)
    }
}
