//Generated by FigmaQML

import QtGraphicalEffects 1.14
import QtQuick 2.14
import QtQuick.Shapes 1.14
Rectangle {
    id: figma_501_227
    objectName:"button/action/normal"
    x:51
    y:120
    width:60
    height:60
    color: "transparent"
    clip: false 
    property Component delegate_501_203:     Shape {
        id: figma_501_203
        objectName:"back_button"
        x:0
        y:0
        width:60
        height:60
        ShapePath {
            strokeColor: "transparent"
            strokeWidth:1
            fillColor:"#ff0889a6"
            id: svgpath_figma_501_203
            fillRule: ShapePath.WindingFill
            PathSvg {
                path: "M60 30C60 46.5685 46.5685 60 30 60C13.4315 60 0 46.5685 0 30C0 13.4315 13.4315 0 30 0C46.5685 0 60 13.4315 60 30Z"
            } 
        }
    }
    property Item i_delegate_501_203
    property matrix4x4 delegate_501_203_transform: Qt.matrix4x4(Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,)
    onDelegate_501_203_transformChanged: {if(i_delegate_501_203 && i_delegate_501_203.transform != delegate_501_203_transform) i_delegate_501_203.transform = delegate_501_203_transform;}
    property real delegate_501_203_x: NaN
    onDelegate_501_203_xChanged: {if(i_delegate_501_203 && i_delegate_501_203.x != delegate_501_203_x) i_delegate_501_203.x = delegate_501_203_x;}
    property real delegate_501_203_y: NaN
    onDelegate_501_203_yChanged: {if(i_delegate_501_203 && i_delegate_501_203.y != delegate_501_203_y) i_delegate_501_203.y = delegate_501_203_y;}
    property real delegate_501_203_width: NaN
    onDelegate_501_203_widthChanged: {if(i_delegate_501_203 && i_delegate_501_203.width != delegate_501_203_width) i_delegate_501_203.width = delegate_501_203_width;}
    property real delegate_501_203_height: NaN
    onDelegate_501_203_heightChanged: {if(i_delegate_501_203 && i_delegate_501_203.height != delegate_501_203_height) i_delegate_501_203.height = delegate_501_203_height;}
    property Component delegate_501_222:     Icon_30_plus_figma {
        id: figma_501_222
        objectName:"icon/30/plus"
        x:15
        y:15
        delegate_501_219:        Rectangle {
            id: figma_i501_222_501_219
            objectName:"plus"
            x:5
            y:5
            width:19
            height:19
            color: "transparent"
            clip: false 
            Shape {
                id: figma_i501_222_501_214
                objectName:"Vector 175"
                x:9
                y:0
                width:0
                height:19
                ShapePath {
                    joinStyle: ShapePath.MiterJoin
                    strokeColor: "#ffffffff"
                    strokeWidth:2
                    fillColor:"transparent"
                    id: svgpath_figma_i501_222_501_214
                    fillRule: ShapePath.WindingFill
                    PathSvg {
                        path: "M1 0C1 -0.552285 0.552285 -1 0 -1C-0.552285 -1 -1 -0.552285 -1 0L1 0ZM-1 19C-1 19.5523 -0.552285 20 0 20C0.552285 20 1 19.5523 1 19L-1 19ZM-1 0L-1 19L1 19L1 0L-1 0Z"
                    } 
                }
            }
            Shape {
                id: figma_i501_222_501_218
                objectName:"Vector 176"
                transform: Matrix4x4 {
                    matrix: Qt.matrix4x4(
                    -4.37114e-08, -1, 19, 0,
                    1, -4.37114e-08, 9.5, 0,
                    0, 0, 1, 0,
                    0, 0, 0, 1)
                }
                x:19
                y:9
                width:0
                height:19
                ShapePath {
                    joinStyle: ShapePath.MiterJoin
                    strokeColor: "#ffffffff"
                    strokeWidth:2
                    fillColor:"transparent"
                    id: svgpath_figma_i501_222_501_218
                    fillRule: ShapePath.WindingFill
                    PathSvg {
                        path: "M1 0C1 -0.552285 0.552285 -1 0 -1C-0.552285 -1 -1 -0.552285 -1 0L1 0ZM-1 19C-1 19.5523 -0.552285 20 0 20C0.552285 20 1 19.5523 1 19L-1 19ZM-1 0L-1 19L1 19L1 0L-1 0Z"
                    } 
                }
            }
        }
    }
    property Item i_delegate_501_222
    property matrix4x4 delegate_501_222_transform: Qt.matrix4x4(Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,)
    onDelegate_501_222_transformChanged: {if(i_delegate_501_222 && i_delegate_501_222.transform != delegate_501_222_transform) i_delegate_501_222.transform = delegate_501_222_transform;}
    property real delegate_501_222_x: NaN
    onDelegate_501_222_xChanged: {if(i_delegate_501_222 && i_delegate_501_222.x != delegate_501_222_x) i_delegate_501_222.x = delegate_501_222_x;}
    property real delegate_501_222_y: NaN
    onDelegate_501_222_yChanged: {if(i_delegate_501_222 && i_delegate_501_222.y != delegate_501_222_y) i_delegate_501_222.y = delegate_501_222_y;}
    property real delegate_501_222_width: NaN
    onDelegate_501_222_widthChanged: {if(i_delegate_501_222 && i_delegate_501_222.width != delegate_501_222_width) i_delegate_501_222.width = delegate_501_222_width;}
    property real delegate_501_222_height: NaN
    onDelegate_501_222_heightChanged: {if(i_delegate_501_222 && i_delegate_501_222.height != delegate_501_222_height) i_delegate_501_222.height = delegate_501_222_height;}
    Component.onCompleted: {
        const o_delegate_501_203 = {}
        if(!isNaN(delegate_501_203_transform.m11)) o_delegate_501_203['transform'] = delegate_501_203_transform;
        if(!isNaN(delegate_501_203_x)) o_delegate_501_203['x'] = delegate_501_203_x;
        if(!isNaN(delegate_501_203_y)) o_delegate_501_203['y'] = delegate_501_203_y;
        if(!isNaN(delegate_501_203_width)) o_delegate_501_203['width'] = delegate_501_203_width;
        if(!isNaN(delegate_501_203_height)) o_delegate_501_203['height'] = delegate_501_203_height;
        i_delegate_501_203 = delegate_501_203.createObject(this, o_delegate_501_203)
        delegate_501_203_x = Qt.binding(()=>i_delegate_501_203.x)
        delegate_501_203_y = Qt.binding(()=>i_delegate_501_203.y)
        delegate_501_203_width = Qt.binding(()=>i_delegate_501_203.width)
        delegate_501_203_height = Qt.binding(()=>i_delegate_501_203.height)
        const o_delegate_501_222 = {}
        if(!isNaN(delegate_501_222_transform.m11)) o_delegate_501_222['transform'] = delegate_501_222_transform;
        if(!isNaN(delegate_501_222_x)) o_delegate_501_222['x'] = delegate_501_222_x;
        if(!isNaN(delegate_501_222_y)) o_delegate_501_222['y'] = delegate_501_222_y;
        if(!isNaN(delegate_501_222_width)) o_delegate_501_222['width'] = delegate_501_222_width;
        if(!isNaN(delegate_501_222_height)) o_delegate_501_222['height'] = delegate_501_222_height;
        i_delegate_501_222 = delegate_501_222.createObject(this, o_delegate_501_222)
        delegate_501_222_x = Qt.binding(()=>i_delegate_501_222.x)
        delegate_501_222_y = Qt.binding(()=>i_delegate_501_222.y)
        delegate_501_222_width = Qt.binding(()=>i_delegate_501_222.width)
        delegate_501_222_height = Qt.binding(()=>i_delegate_501_222.height)
    }
}
