//Generated by FigmaQML

import QtGraphicalEffects 1.14
import QtQuick 2.14
import QtQuick.Shapes 1.14
Rectangle {
    id: figma_501_191
    objectName:"button/simple/normal"
    x:51
    y:212
    width:60
    height:60
    color: "transparent"
    clip: false 
    property Component delegate_501_163:     Shape {
        id: figma_501_163
        objectName:"back_button"
        x:0
        y:0
        width:60
        height:60
        ShapePath {
            strokeColor: "transparent"
            strokeWidth:1
            fillColor:"#ffb0d1d8"
            id: svgpath_figma_501_163
            fillRule: ShapePath.WindingFill
            PathSvg {
                path: "M60 30C60 46.5685 46.5685 60 30 60C13.4315 60 0 46.5685 0 30C0 13.4315 13.4315 0 30 0C46.5685 0 60 13.4315 60 30Z"
            } 
        }
    }
    property Item i_delegate_501_163
    property matrix4x4 delegate_501_163_transform: Qt.matrix4x4(Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,)
    onDelegate_501_163_transformChanged: {if(i_delegate_501_163 && i_delegate_501_163.transform != delegate_501_163_transform) i_delegate_501_163.transform = delegate_501_163_transform;}
    property real delegate_501_163_x: NaN
    onDelegate_501_163_xChanged: {if(i_delegate_501_163 && i_delegate_501_163.x != delegate_501_163_x) i_delegate_501_163.x = delegate_501_163_x;}
    property real delegate_501_163_y: NaN
    onDelegate_501_163_yChanged: {if(i_delegate_501_163 && i_delegate_501_163.y != delegate_501_163_y) i_delegate_501_163.y = delegate_501_163_y;}
    property real delegate_501_163_width: NaN
    onDelegate_501_163_widthChanged: {if(i_delegate_501_163 && i_delegate_501_163.width != delegate_501_163_width) i_delegate_501_163.width = delegate_501_163_width;}
    property real delegate_501_163_height: NaN
    onDelegate_501_163_heightChanged: {if(i_delegate_501_163 && i_delegate_501_163.height != delegate_501_163_height) i_delegate_501_163.height = delegate_501_163_height;}
    property Component delegate_501_187:     Text {
        id: figma_501_187
        objectName:"text_button"
        x:15
        y:15
        width:30
        height:30
        color:"#ff024873"
        wrapMode: TextEdit.WordWrap
        text:"2"
        font.family: "MS Shell Dlg 2"
        font.italic: false
        font.letterSpacing: 1
        font.pixelSize: 24
        font.weight: Font.Normal
        horizontalAlignment: Text.AlignHCenter
        verticalAlignment: Text.AlignBottom
    }
    property Item i_delegate_501_187
    property matrix4x4 delegate_501_187_transform: Qt.matrix4x4(Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,)
    onDelegate_501_187_transformChanged: {if(i_delegate_501_187 && i_delegate_501_187.transform != delegate_501_187_transform) i_delegate_501_187.transform = delegate_501_187_transform;}
    property real delegate_501_187_x: NaN
    onDelegate_501_187_xChanged: {if(i_delegate_501_187 && i_delegate_501_187.x != delegate_501_187_x) i_delegate_501_187.x = delegate_501_187_x;}
    property real delegate_501_187_y: NaN
    onDelegate_501_187_yChanged: {if(i_delegate_501_187 && i_delegate_501_187.y != delegate_501_187_y) i_delegate_501_187.y = delegate_501_187_y;}
    property real delegate_501_187_width: NaN
    onDelegate_501_187_widthChanged: {if(i_delegate_501_187 && i_delegate_501_187.width != delegate_501_187_width) i_delegate_501_187.width = delegate_501_187_width;}
    property real delegate_501_187_height: NaN
    onDelegate_501_187_heightChanged: {if(i_delegate_501_187 && i_delegate_501_187.height != delegate_501_187_height) i_delegate_501_187.height = delegate_501_187_height;}
    Component.onCompleted: {
        const o_delegate_501_163 = {}
        if(!isNaN(delegate_501_163_transform.m11)) o_delegate_501_163['transform'] = delegate_501_163_transform;
        if(!isNaN(delegate_501_163_x)) o_delegate_501_163['x'] = delegate_501_163_x;
        if(!isNaN(delegate_501_163_y)) o_delegate_501_163['y'] = delegate_501_163_y;
        if(!isNaN(delegate_501_163_width)) o_delegate_501_163['width'] = delegate_501_163_width;
        if(!isNaN(delegate_501_163_height)) o_delegate_501_163['height'] = delegate_501_163_height;
        i_delegate_501_163 = delegate_501_163.createObject(this, o_delegate_501_163)
        delegate_501_163_x = Qt.binding(()=>i_delegate_501_163.x)
        delegate_501_163_y = Qt.binding(()=>i_delegate_501_163.y)
        delegate_501_163_width = Qt.binding(()=>i_delegate_501_163.width)
        delegate_501_163_height = Qt.binding(()=>i_delegate_501_163.height)
        const o_delegate_501_187 = {}
        if(!isNaN(delegate_501_187_transform.m11)) o_delegate_501_187['transform'] = delegate_501_187_transform;
        if(!isNaN(delegate_501_187_x)) o_delegate_501_187['x'] = delegate_501_187_x;
        if(!isNaN(delegate_501_187_y)) o_delegate_501_187['y'] = delegate_501_187_y;
        if(!isNaN(delegate_501_187_width)) o_delegate_501_187['width'] = delegate_501_187_width;
        if(!isNaN(delegate_501_187_height)) o_delegate_501_187['height'] = delegate_501_187_height;
        i_delegate_501_187 = delegate_501_187.createObject(this, o_delegate_501_187)
        delegate_501_187_x = Qt.binding(()=>i_delegate_501_187.x)
        delegate_501_187_y = Qt.binding(()=>i_delegate_501_187.y)
        delegate_501_187_width = Qt.binding(()=>i_delegate_501_187.width)
        delegate_501_187_height = Qt.binding(()=>i_delegate_501_187.height)
    }
}
