//Generated by FigmaQML

import QtGraphicalEffects 1.14
import QtQuick 2.14
import QtQuick.Shapes 1.14
Rectangle {
    id: figma_501_422
    objectName:"button/cancel/active"
    x:215
    y:212
    width:60
    height:60
    color: "transparent"
    clip: false 
    property Component delegate_501_420:     Shape {
        id: figma_501_420
        objectName:"back_button"
        x:0
        y:0
        width:60
        height:60
        ShapePath {
            strokeColor: "transparent"
            strokeWidth:1
            fillColor:"#fff25e5e"
            id: svgpath_figma_501_420
            fillRule: ShapePath.WindingFill
            PathSvg {
                path: "M60 30C60 46.5685 46.5685 60 30 60C13.4315 60 0 46.5685 0 30C0 13.4315 13.4315 0 30 0C46.5685 0 60 13.4315 60 30Z"
            } 
        }
    }
    property Item i_delegate_501_420
    property matrix4x4 delegate_501_420_transform: Qt.matrix4x4(Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,)
    onDelegate_501_420_transformChanged: {if(i_delegate_501_420 && i_delegate_501_420.transform != delegate_501_420_transform) i_delegate_501_420.transform = delegate_501_420_transform;}
    property real delegate_501_420_x: NaN
    onDelegate_501_420_xChanged: {if(i_delegate_501_420 && i_delegate_501_420.x != delegate_501_420_x) i_delegate_501_420.x = delegate_501_420_x;}
    property real delegate_501_420_y: NaN
    onDelegate_501_420_yChanged: {if(i_delegate_501_420 && i_delegate_501_420.y != delegate_501_420_y) i_delegate_501_420.y = delegate_501_420_y;}
    property real delegate_501_420_width: NaN
    onDelegate_501_420_widthChanged: {if(i_delegate_501_420 && i_delegate_501_420.width != delegate_501_420_width) i_delegate_501_420.width = delegate_501_420_width;}
    property real delegate_501_420_height: NaN
    onDelegate_501_420_heightChanged: {if(i_delegate_501_420 && i_delegate_501_420.height != delegate_501_420_height) i_delegate_501_420.height = delegate_501_420_height;}
    property Component delegate_501_421:     Text {
        id: figma_501_421
        objectName:"text_button"
        x:14
        y:15
        width:30
        height:30
        color:"#ffffffff"
        wrapMode: TextEdit.WordWrap
        text:"C"
        font.family: "MS Shell Dlg 2"
        font.italic: false
        font.letterSpacing: 1
        font.pixelSize: 24
        font.weight: Font.Normal
        horizontalAlignment: Text.AlignHCenter
        verticalAlignment: Text.AlignBottom
    }
    property Item i_delegate_501_421
    property matrix4x4 delegate_501_421_transform: Qt.matrix4x4(Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,)
    onDelegate_501_421_transformChanged: {if(i_delegate_501_421 && i_delegate_501_421.transform != delegate_501_421_transform) i_delegate_501_421.transform = delegate_501_421_transform;}
    property real delegate_501_421_x: NaN
    onDelegate_501_421_xChanged: {if(i_delegate_501_421 && i_delegate_501_421.x != delegate_501_421_x) i_delegate_501_421.x = delegate_501_421_x;}
    property real delegate_501_421_y: NaN
    onDelegate_501_421_yChanged: {if(i_delegate_501_421 && i_delegate_501_421.y != delegate_501_421_y) i_delegate_501_421.y = delegate_501_421_y;}
    property real delegate_501_421_width: NaN
    onDelegate_501_421_widthChanged: {if(i_delegate_501_421 && i_delegate_501_421.width != delegate_501_421_width) i_delegate_501_421.width = delegate_501_421_width;}
    property real delegate_501_421_height: NaN
    onDelegate_501_421_heightChanged: {if(i_delegate_501_421 && i_delegate_501_421.height != delegate_501_421_height) i_delegate_501_421.height = delegate_501_421_height;}
    Component.onCompleted: {
        const o_delegate_501_420 = {}
        if(!isNaN(delegate_501_420_transform.m11)) o_delegate_501_420['transform'] = delegate_501_420_transform;
        if(!isNaN(delegate_501_420_x)) o_delegate_501_420['x'] = delegate_501_420_x;
        if(!isNaN(delegate_501_420_y)) o_delegate_501_420['y'] = delegate_501_420_y;
        if(!isNaN(delegate_501_420_width)) o_delegate_501_420['width'] = delegate_501_420_width;
        if(!isNaN(delegate_501_420_height)) o_delegate_501_420['height'] = delegate_501_420_height;
        i_delegate_501_420 = delegate_501_420.createObject(this, o_delegate_501_420)
        delegate_501_420_x = Qt.binding(()=>i_delegate_501_420.x)
        delegate_501_420_y = Qt.binding(()=>i_delegate_501_420.y)
        delegate_501_420_width = Qt.binding(()=>i_delegate_501_420.width)
        delegate_501_420_height = Qt.binding(()=>i_delegate_501_420.height)
        const o_delegate_501_421 = {}
        if(!isNaN(delegate_501_421_transform.m11)) o_delegate_501_421['transform'] = delegate_501_421_transform;
        if(!isNaN(delegate_501_421_x)) o_delegate_501_421['x'] = delegate_501_421_x;
        if(!isNaN(delegate_501_421_y)) o_delegate_501_421['y'] = delegate_501_421_y;
        if(!isNaN(delegate_501_421_width)) o_delegate_501_421['width'] = delegate_501_421_width;
        if(!isNaN(delegate_501_421_height)) o_delegate_501_421['height'] = delegate_501_421_height;
        i_delegate_501_421 = delegate_501_421.createObject(this, o_delegate_501_421)
        delegate_501_421_x = Qt.binding(()=>i_delegate_501_421.x)
        delegate_501_421_y = Qt.binding(()=>i_delegate_501_421.y)
        delegate_501_421_width = Qt.binding(()=>i_delegate_501_421.width)
        delegate_501_421_height = Qt.binding(()=>i_delegate_501_421.height)
    }
}
