//Generated by FigmaQML

import QtGraphicalEffects 1.14
import QtQuick 2.14
import QtQuick.Shapes 1.14
Rectangle {
    id: figma_501_512
    objectName:"icon/30/percent"
    x:261
    y:75
    width:30
    height:30
    color: "transparent"
    clip: false 
    property Component delegate_501_505:     Shape {
        id: figma_501_505
        objectName:"back_action"
        x:0
        y:0
        width:30
        height:30
        ShapePath {
            strokeColor: "transparent"
            strokeWidth:1
            fillColor:"transparent"
            id: svgpath_figma_501_505
        }
    }
    property Item i_delegate_501_505
    property matrix4x4 delegate_501_505_transform: Qt.matrix4x4(Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,)
    onDelegate_501_505_transformChanged: {if(i_delegate_501_505 && i_delegate_501_505.transform != delegate_501_505_transform) i_delegate_501_505.transform = delegate_501_505_transform;}
    property real delegate_501_505_x: NaN
    onDelegate_501_505_xChanged: {if(i_delegate_501_505 && i_delegate_501_505.x != delegate_501_505_x) i_delegate_501_505.x = delegate_501_505_x;}
    property real delegate_501_505_y: NaN
    onDelegate_501_505_yChanged: {if(i_delegate_501_505 && i_delegate_501_505.y != delegate_501_505_y) i_delegate_501_505.y = delegate_501_505_y;}
    property real delegate_501_505_width: NaN
    onDelegate_501_505_widthChanged: {if(i_delegate_501_505 && i_delegate_501_505.width != delegate_501_505_width) i_delegate_501_505.width = delegate_501_505_width;}
    property real delegate_501_505_height: NaN
    onDelegate_501_505_heightChanged: {if(i_delegate_501_505 && i_delegate_501_505.height != delegate_501_505_height) i_delegate_501_505.height = delegate_501_505_height;}
    property Component delegate_501_536:     Rectangle {
        id: figma_501_536
        objectName:"percent"
        x:6
        y:6
        width:18
        height:18
        color: "transparent"
        clip: false 
        Shape {
            id: figma_501_515
            objectName:"Vector 177"
            x:4
            y:1
            width:10
            height:16
            ShapePath {
                joinStyle: ShapePath.MiterJoin
                strokeColor: "#ffffffff"
                strokeWidth:2
                fillColor:"transparent"
                id: svgpath_figma_501_515
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M10.848 0.529999C11.1407 0.0616624 10.9983 -0.555288 10.53 -0.847998C10.0617 -1.14071 9.44471 -0.998335 9.152 -0.529999L10.848 0.529999ZM-0.847998 15.47C-1.14071 15.9383 -0.998335 16.5553 -0.529999 16.848C-0.0616624 17.1407 0.555288 16.9983 0.847998 16.53L-0.847998 15.47ZM9.152 -0.529999L-0.847998 15.47L0.847998 16.53L10.848 0.529999L9.152 -0.529999Z"
                } 
            }
        }
        Shape {
            id: figma_501_521
            objectName:"Ellipse 278"
            x:12
            y:10
            width:6
            height:8
            ShapePath {
                joinStyle: ShapePath.MiterJoin
                strokeColor: "#ffffffff"
                strokeWidth:2
                fillColor:"transparent"
                id: svgpath_figma_501_521
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M5 4C5 4.90912 4.72237 5.69369 4.32132 6.22843C3.9205 6.76286 3.4431 7 3 7L3 9C4.21375 9 5.23636 8.34171 5.92132 7.42843C6.60605 6.51545 7 5.30002 7 4L5 4ZM3 7C2.5569 7 2.0795 6.76286 1.67868 6.22843C1.27762 5.69369 1 4.90912 1 4L-1 4C-1 5.30002 -0.606052 6.51545 0.0786797 7.42843C0.763642 8.34171 1.78625 9 3 9L3 7ZM1 4C1 3.09088 1.27762 2.30631 1.67868 1.77157C2.0795 1.23714 2.5569 1 3 1L3 -1C1.78625 -1 0.763642 -0.34171 0.0786797 0.571573C-0.606052 1.48455 -1 2.69998 -1 4L1 4ZM3 1C3.4431 1 3.9205 1.23714 4.32132 1.77157C4.72237 2.30631 5 3.09088 5 4L7 4C7 2.69998 6.60605 1.48455 5.92132 0.571573C5.23636 -0.34171 4.21375 -1 3 -1L3 1Z"
                } 
            }
        }
        Shape {
            id: figma_501_526
            objectName:"Ellipse 279"
            x:0
            y:0
            width:6
            height:8
            ShapePath {
                joinStyle: ShapePath.MiterJoin
                strokeColor: "#ffffffff"
                strokeWidth:2
                fillColor:"transparent"
                id: svgpath_figma_501_526
                fillRule: ShapePath.WindingFill
                PathSvg {
                    path: "M5 4C5 4.90912 4.72237 5.69369 4.32132 6.22843C3.9205 6.76286 3.4431 7 3 7L3 9C4.21375 9 5.23636 8.34171 5.92132 7.42843C6.60605 6.51545 7 5.30002 7 4L5 4ZM3 7C2.5569 7 2.0795 6.76286 1.67868 6.22843C1.27762 5.69369 1 4.90912 1 4L-1 4C-1 5.30002 -0.606052 6.51545 0.0786797 7.42843C0.763642 8.34171 1.78625 9 3 9L3 7ZM1 4C1 3.09088 1.27762 2.30631 1.67868 1.77157C2.0795 1.23714 2.5569 1 3 1L3 -1C1.78625 -1 0.763642 -0.34171 0.0786797 0.571573C-0.606052 1.48455 -1 2.69998 -1 4L1 4ZM3 1C3.4431 1 3.9205 1.23714 4.32132 1.77157C4.72237 2.30631 5 3.09088 5 4L7 4C7 2.69998 6.60605 1.48455 5.92132 0.571573C5.23636 -0.34171 4.21375 -1 3 -1L3 1Z"
                } 
            }
        }
    }
    property Item i_delegate_501_536
    property matrix4x4 delegate_501_536_transform: Qt.matrix4x4(Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,)
    onDelegate_501_536_transformChanged: {if(i_delegate_501_536 && i_delegate_501_536.transform != delegate_501_536_transform) i_delegate_501_536.transform = delegate_501_536_transform;}
    property real delegate_501_536_x: NaN
    onDelegate_501_536_xChanged: {if(i_delegate_501_536 && i_delegate_501_536.x != delegate_501_536_x) i_delegate_501_536.x = delegate_501_536_x;}
    property real delegate_501_536_y: NaN
    onDelegate_501_536_yChanged: {if(i_delegate_501_536 && i_delegate_501_536.y != delegate_501_536_y) i_delegate_501_536.y = delegate_501_536_y;}
    property real delegate_501_536_width: NaN
    onDelegate_501_536_widthChanged: {if(i_delegate_501_536 && i_delegate_501_536.width != delegate_501_536_width) i_delegate_501_536.width = delegate_501_536_width;}
    property real delegate_501_536_height: NaN
    onDelegate_501_536_heightChanged: {if(i_delegate_501_536 && i_delegate_501_536.height != delegate_501_536_height) i_delegate_501_536.height = delegate_501_536_height;}
    Component.onCompleted: {
        const o_delegate_501_505 = {}
        if(!isNaN(delegate_501_505_transform.m11)) o_delegate_501_505['transform'] = delegate_501_505_transform;
        if(!isNaN(delegate_501_505_x)) o_delegate_501_505['x'] = delegate_501_505_x;
        if(!isNaN(delegate_501_505_y)) o_delegate_501_505['y'] = delegate_501_505_y;
        if(!isNaN(delegate_501_505_width)) o_delegate_501_505['width'] = delegate_501_505_width;
        if(!isNaN(delegate_501_505_height)) o_delegate_501_505['height'] = delegate_501_505_height;
        i_delegate_501_505 = delegate_501_505.createObject(this, o_delegate_501_505)
        delegate_501_505_x = Qt.binding(()=>i_delegate_501_505.x)
        delegate_501_505_y = Qt.binding(()=>i_delegate_501_505.y)
        delegate_501_505_width = Qt.binding(()=>i_delegate_501_505.width)
        delegate_501_505_height = Qt.binding(()=>i_delegate_501_505.height)
        const o_delegate_501_536 = {}
        if(!isNaN(delegate_501_536_transform.m11)) o_delegate_501_536['transform'] = delegate_501_536_transform;
        if(!isNaN(delegate_501_536_x)) o_delegate_501_536['x'] = delegate_501_536_x;
        if(!isNaN(delegate_501_536_y)) o_delegate_501_536['y'] = delegate_501_536_y;
        if(!isNaN(delegate_501_536_width)) o_delegate_501_536['width'] = delegate_501_536_width;
        if(!isNaN(delegate_501_536_height)) o_delegate_501_536['height'] = delegate_501_536_height;
        i_delegate_501_536 = delegate_501_536.createObject(this, o_delegate_501_536)
        delegate_501_536_x = Qt.binding(()=>i_delegate_501_536.x)
        delegate_501_536_y = Qt.binding(()=>i_delegate_501_536.y)
        delegate_501_536_width = Qt.binding(()=>i_delegate_501_536.width)
        delegate_501_536_height = Qt.binding(()=>i_delegate_501_536.height)
    }
}
